### ISSUE TITLE
Issue with Non-conforming DI Container integration with constructor injected services

### ISSUE THREAD

**Issue by mpickers** [FastEndpoints/FastEndpoints#289]
After I noticed the PR by Simple Injector's Steven (@dotnetjunkie) was merged, I gave the lastest Fastendpoints a whirl with SimpleInjector as described in the PR:
https://github.com/FastEndpoints/FastEndpoints/pull/243
and similar info here: https://github.com/simpleinjector/SimpleInjector/issues/955#issuecomment-1254827842

However, using the example code below, it seems if you inject an application service into your endpoint, the MS DI container will complain that it can't resolve the service. Whilst this makes technical sense since we haven't registered the application service in the DI container, we have instead registered it in SimpleInjector, it doesn't help in being able to use SimpleInjector to resolve the endpoints and services.

The only work-around that I can see is to register the application services in the MS DI container as well - which doesn't seem correct.

Whilst the new IEndpointFactory seems to work (if you work around the MS DI registration issue) and resolves with SimpleInjector, it would seem that perhaps something else is needed in the **AddFastEndpoints()** method to either allow a different DI service registration or to skip the registration of the Endpoints in the MS DI container ?

### Example
Example has been adapted from the Fastendpoints startup example:

```c#
global using FastEndpoints;
using SimpleInjector;

var container = new Container();

var builder = WebApplication.CreateBuilder();

// Setup FastEndpoints
builder.Services
       .AddFastEndpoints();

// NOTE: By this stage, MyEndpoint has been registered in the MS DI!

// Setup Simple Injector
builder.Services
       .AddSingleton<IEndpointFactory, SimpleInjectorEndpointFactory>()
       .AddSimpleInjector(container, options =>
                                     {
                                        options.AddAspNetCore();
                                     });

// Register our service and Endpoint with SimpleInjector
container.RegisterSingleton<MyService>();
container.Register<MyEndpoint>();


// If the next line is uncommented, the MS DI container can correctly verify - but then we've essentially duplicated the
// registrations in the MS DI container and the SimpleInjector container.
//builder.Services.AddSingleton<MyService>();

// Fails here due to the application service not being registered in the MS DI container - which makes sense.
// Error:
// Some services are not able to be constructed (Error while validating the service descriptor
// 'ServiceType: MyEndpoint Lifetime: Transient ImplementationType: MyEndpoint':
// Unable to resolve service for type 'MyService' while attempting to activate 'MyEndpoint'.)
// (Error while validating the service descriptor 'ServiceType: MyWebApp.MyEndpoint Lifetime: Transient ImplementationType: MyWebApp.MyEndpoint':
// Unable to resolve service for type 'MyService' while attempting to activate 'MyWebApp.MyEndpoint'.)
var app = builder.Build();

app.UseAuthorization()
   .UseFastEndpoints()
   .UseSimpleInjector(container);

container.Verify();

app.Run();


public record SimpleInjectorEndpointFactory(Container Container) : IEndpointFactory
{
   public BaseEndpoint Create(EndpointDefinition def, HttpContext ctx) =>
      (BaseEndpoint)Container.GetInstance(def.EndpointType);
}


public class MyService
{
   public async Task<string> GetVersion()
   {
      return await Task.FromResult("v1.0");
   }
}

public class MyEndpoint : Endpoint<MyRequest>
{
   private readonly MyService _svc;

   // Injecting the application service, MyService into our endpoint.
   public MyEndpoint(MyService svc)
   {
      _svc = svc;
   }

   public override void Configure()
   {
      Post("/api/user/create");
      AllowAnonymous();
   }

   public override async Task HandleAsync(MyRequest req, CancellationToken ct)
   {
      var v = await _svc.GetVersion();

      var response = new MyResponse()
                     {
                        FullName = req.FirstName + " " + req.LastName + " " + v,
                        IsOver18 = req.Age > 18
                     };

      await SendAsync(response);
   }
}

public class MyRequest
{
   public string FirstName { get; set; }
   public string LastName { get; set; }
   public int Age { get; set; }
}

public class MyResponse
{
   public string FullName { get; set; }
   public bool IsOver18 { get; set; }
}
```

**Comment by dj-nitehawk** [comment]
i believe the correct way to use simpleinjector is to register the simpleinjector container with MS DI and then resolve the container first in fastendpoints and then use the injected container to resolve any needed services.

@dotnetjunkie pls correct me if i'm wrong.

any other way would just not be possible because it's a "non-conforming" IOC lib. and fastendpoints does not have any knowledge of simpleinjector, nor will it ever will.

**Comment by mpickers** [comment]
Thanks for your time and prompt response.

>  is to register the simpleinjector container with MS DI

This line will register the SimpleInjector container in the MS DI and link SimpleInjector to the MS DI container so that if a request is made to the SimpleInjector container and it can't resolve the instance, it will ask the MS DI container to resolve it.
```c#
.AddSimpleInjector(container, options =>
                                     {
                                        options.AddAspNetCore();
                                     });
```
> and then resolve the container first in fastendpoints and then use the injected container to resolve any needed services.

I'm not sure what you are meaning here?

> and fastendpoints does not have any knowledge of simpleinjector, nor will it ever.

Fair enough regarding not wanting to have knowledge of simpleinjector. I agree. The question then is why have the IEndpointFactory? Is it just to allow you to do something else weird with the Endpoint creation?

I'm trying to figure out what I'm missing?

### Further DI registration thoughts...
I had a play around with removing the Endpoints from the MS DI container once Fastendpoints registers the Endpoints (from EndpointData creation). That way the MS DI can verify correctly, but the resolution of the Endpoints is then done by the SimpleInjectorEndpointFactory.

It's not elegant and assumes funky things wont be done in Fastendpoints in the future. eg as a POC

```c#
// Setup FastEndpoints
builder.Services
       .AddFastEndpoints();

// Remove the unneeded IEndpoint registrations in the MS DI container
var endpointRegos = builder.Services.Where(descriptor => descriptor.ServiceType.GetInterface(nameof(IEndpoint)) != null).
                            ToList();

foreach (var r in endpointRegos)
{
   builder.Services.Remove(r);
}
```

Digging into the Fastendpoints code, there could be the potential to add to EndpointDiscoveryOptions to skip the "actual" registration. Then in BuildEndpointDefinitions check for that option. eg

```c#
EndpointDiscoveryOptions.SkipEndpointRegistration = true;

//... in BuildEndpointDefinitions()
if (!options.SkipEndpointRegistration)
{
   services.AddTransient(t);
}
//...

```

or a step further and separate out the registration from the discovery. The registration then being done on the results of that discovery. Still having a skip registration option:

eg
```c#
    public static IServiceCollection AddFastEndpoints(this IServiceCollection services,
        Action<EndpointDiscoveryOptions>? options = null,
        ConfigurationManager? config = null)
    {
        var opts = new EndpointDiscoveryOptions();
        options?.Invoke(opts);
        Endpoints = new(services, opts, config);

// Register the discovered endpoints
if (!opts.SkipEndpointRegistration)
{
   foreach (var epDef in Endpoints.Found)
   {
      services.AddTransient(epDef.EndpointType);
   }
}

        services.AddAuthorization(BuildSecurityPoliciesForEndpoints); //this method doesn't block
        services.AddHttpContextAccessor(); //todo: remove after removing scoped validator support.
        services.AddSingleton<IEndpointFactory, EndpointFactory>();
        services.TryAddSingleton(typeof(IRequestBinder<>), typeof(RequestBinder<>));
        services.AddSingleton(typeof(Event<>));
        return services;
    }
```

I maybe missing something here, so I'm interested in thoughts around this.

Cheers

**Comment by dotnetjunkie** [comment]
Hi guys, I'm in a different time zone so my apologizes for replying a bit late.

The problem here is caused the MS.DI container registrations becoming incomplete, because FastEndpoints still registers the endpoints (even though Simple Injector creates them), while its dependencies will not be registered (as they are registered in Simple Injector).

This is a problem that, for MS.DI, only exists during development, because in production this verification step is omitted. Still, I would discourage from suppressing validation during debugging, because I deem such feature vital to be productive as developer. Simple Injector contains such verification feature for a very long time already.

I would say that in case a non-default mechanism is used (i.e. endpoints being resolved from Simple Injector), those endpoints should not be registered any longer in the default MS.DI container, especially in order to be able to verify the MS.DI registrations.

It means that those registrations must be removed again 'manually', much like @mpickers did above:

``` c#
// Move registrations to Simple Injector
var endpoints = builder.Services.Where(s => typeof(BaseEndpoint).IsAssignableFrom(s.ServiceType));

foreach (var endpoint in endpoints.ToArray())
{
    builder.Services.Remove(endpoint);
    container.Register(endpoint.ImplementationType!);
}
```

I will update the samples on the Simple Injector page.

**Comment by dotnetjunkie** [comment]
@dj-nitehawk, 

In the future, I could imagine FastEndpoints users to be able override or influence the way that FastEndpoints registers its endpoints in the MS.DI container and allow them to *not* being registered. But I would like to stress that *not* having such feature shouldn't be that big of a deal. For Simple Injector, for instance, I provided the 'workaround' above and for other non-conforming containers the solution would be similar.

By adding an `IEndpointFactory` you enabled non-conforming and other interception scenarios, which is a big plus. It isn't that weird for users that deviate from the default must to 'some extra work' to get things running. Again, thanks to the new flexibility there are now a lot of new possibilities.

If you decide to add the ability to override registration, I'm happy to exchange some ideas on how this can be achieved.

But there are other options to explore.

Another option for FastEndpoints is to *not* register endpoints *at all*. Might seem weird, but many of the Microsoft .NET Core frameworks actually take this approach and instead of calling into `IServiceProvider.GetService`, they create their root types by calling `ActivatorUtilities.CreateInstance`. Take a look, for instance, at ASP.NET Core MVC and SignalR Core for instance; they both take this approach. I believe that in MVC, there's a default `IControllerFactory` implementation that calls `ActivatorUtilities` (or uses some optimized implementation of that).

Do keep in mind that not registering the root types (as MVC and SignalR do) has its downsides of its own, which is that you are losing the ability to verify them with their dependencies (which is a problem that currently exists with MVC and SignalR). The non-registration design for MVC was picked with .NET Core 1.0, while verification only was added in .NET Core 3.0, so that might explain that design choice a bit. But this is one of the reasons why MVC allows controllers to be explicitly registered by calling `AddMvcControllersAsServices()` (which I think that every MVC developer should do).

But I can imagine FastEndpoints taking a similar root where `ActivatorUtilities.Create` is the default method, while developers can call `AddEndpointsAsServices()` can be called to get the endpoints into MS.DI. This means that non-conformers can simply skip calling `AddEndpointsAsServices()`. We could argue about this, but at least it is very much in sync with what Microsoft is doing.

**Comment by dj-nitehawk** [comment]
so... i removed the endpoint di registration from the startup/discovery and switched to using `ActivatorUtilities.CreateFactory()` in `v5.2.1.8-beta`.

this should do the trick for now right?

**Comment by dotnetjunkie** [comment]
> this should do the trick for now right?

Certainly, as long as you considered the consequences of not having endpoints as explicitly registered root types.

**Comment by mpickers** [comment]
Happy to see I wasn't going mad and on the right track with my thinking.

@dj-nitehawk Thanks for the tweak! I'll give it a spin.

I do tend to agree with @dotnetjunkie in regards to the possibility of container registration and verification down the track by way of some hook-in point for acting on the discovered Endpoint types.

**Comment by dj-nitehawk** [comment]
> Certainly, as long as you considered the consequences of not having endpoints as explicitly registered root types

yeah i don't think that's a big deal. only reason they were registered in DI was to support ctor injection on them. which now the discovery of `ActivatorUtilities` takes care of. i wasn't aware of that until you mentioned it. thanks for that!

> I can confirm v5.2.1.8-beta works as per above discussions with SimpleInjector. Thanks!

great!

thanks everyone for your input.

**Comment by dj-nitehawk** [comment]
hey guys...

with the latest beta FE now uses a "service resolver proxy" interface to obtain services from DI.

https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Library/Config/IServiceResolver.cs

it's not 100% there yet but should help with simpleinjector. 

you can register your own `IServiceResolver` implementation which wraps around simpleinjector calls.

here's the default implementation which gets stuff out of MS DI.

https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Library/Config/ServiceResolver.cs

**Comment by dotnetjunkie** [comment]
Is that new `IServiceResolver` interface meant to be called by FastEndpoints for *all* its services? If so, this is likely not going to help any non-conforming containers (e.g. Simple Injector, Castle Windsor, etc), because it still assumes the built-in container is completely replaced with the non-conforming container, which will never be the case. A non-conforming container is non conforming because it can't comply to the specification of the built-in DI abstraction, because it behaves in an incompatible manner. This can cause subtle but hard to fix issues, because FastEndpoints will for this service still expect the built-in DI behavior.

Besides, there already exists an abstraction just like your `IServiceResolver`, which does the same. It's called `IServiceProvider`. As far as I see, if you would allow the `IServiceProvider` to be replaced with a custom one, you'd likely achieve exactly the same.

Although allowing to replace/intercept calls to `IServiceProvider` (by providing a custom implementation for a non-conforming container) might have its use, it will typically still be rather awkward to create an implementation for a non-conforming container, because most of the FastEndpoints registrations will (and arguably *should*) be part of the built-in DI Container. This means that the custom `IServiceProvider` (or `IServiceResolver` as you will) implementation must switch internally between resolving from the built-in container or the developer's application container (i.e. the non-conforming container).

I hope this makes sense. If I'm misinterpreting what `IServiceResolver` is for, please let me know.

**Comment by dj-nitehawk** [comment]
@dotnetjunkie yeah i see your point.
well.. it was done for a different purpose anyway.
