### ISSUE TITLE
Can FastEndpoints create endpoints dynamically on start up?

### ISSUE THREAD

**Issue by MarioGK** [FastEndpoints/FastEndpoints#307]
Is there something similar to `IAplicationFeatureProvider<ControllerFeature>` where you can create types and create them dynamically?

**Comment by dj-nitehawk** [comment]
not sure if this will do the job but FE is delegating out the endpoint creation/instantiating to a factory class which is being registered in DI:

https://github.com/FastEndpoints/FastEndpoints/blob/f29fcd24cf3220c6f8027fb33cb884d392dc41b8/Src/Library/Main/MainExtensions.cs#L39

but i doubt it will be useful because we do the following in the assembly scanning phase of startup:
https://github.com/FastEndpoints/FastEndpoints/blob/f29fcd24cf3220c6f8027fb33cb884d392dc41b8/Src/Library/Main/EndpointData.cs#L114-L129

so i guess the short answer is no.
