### ISSUE TITLE
[Question] What exactly is used for a "TokenSigningKey"

### ISSUE THREAD

**Issue by isilcala** [FastEndpoints/FastEndpoints#336]
Hi,

This must be a dumb question. But what exactly is used for "TokenSigningKey"?

With the online JWK generator I get JWKs like this:
`{
    "keys": [
        {
            "p": "u0g8-i0KYqOE0T2Sg9aFJu2vo5AXKvvMk2EfuwtUf59pdRW4ESUtmIoXHPZbvin_niQFcJ43agROEU0V2Du-yiTNEPvr1HBAO70OQkKnZTdi6kqoEy6_gWvVhoA9dVnDd_REerduaUgKH9xl76ono4Jd_tUWRS_HvkPmKYJSAjM",
            "kty": "RSA",
            "q": "txcg3hRU6we1r5AwAfzq3VCjVIcV1qyBLANBWwd-AjUuobHJFdj2RadcpA9bay4ektL-OIzPSUjMqmdX1dCQfMApKb82LOJp9NMkNTZ01zozRuVA-sK89rehRmswjyM0vywErjGbU9-l_B4_KuWxH8lmAtVc78MvMKmX6KGcGW8",
            "d": "bEWHXD-wQ6_2tU0qt_zqid22d3IUiKhlFM9jY36360nEFl28tL3PioXYas3S-R9PgJWTyyUpoH5nev8eoTC_bIbLs-6rW4ePnvLLxghL8FxyWwbRkLFskrakAvUGQpaHhiwmjKUtOWsWYiA3uVPtl0gPKr1gxevBGtFnWvVU2vEx0x3Em7GYLor8m0mcacGVVIDRczoiNNeOFSCU-TCPxQS96z3_m8MqCtcNOPSQcCe2Vv5D00XWgvIHmHZK-5GlMWxxCsjcuO0WpLgqs7fPGHmzkP9BsS53ZJsSjgO1asS5OsvS8zkHN1dRLY_zOlF5CBZNx6ww5dsHdsCWBQMMQQ",
            "e": "AQAB",
            "qi": "kGaLgZ2LN0Y7mi-4qCOPYlkA_h4-e2TtrF6zepJhmDS4bXrTCtMVVNW0YvXxn5H3Uocu-P-RIm7I_uAW7WmSz1Jncnmx8X1hFoe6cHIfLO3jov8ocZxAnayhfZq6B9m2dHsCyn90-yjiOukmy6PIS6P_7sxf1cv1tVeyuYGfSWQ",
            "dp": "QscXNv0oXtN_YDxcKbYr9B18Kw4NtL3jzAktjzwS_Q6SQ7Vi1Ho1L9bNNv6A5-WBx5mAdw9zItI2I-UgjOGAvgMxO4UYKb98p9BZbTbnCSgelPvZwj1A-5y_nh3LzDQdhoAKitcs_004jvO_RR2e1KZ_bYX9Ut4ekrETOGnHZBE",
            "dq": "MZL4mkklCRJoVmYTKaairVQVNWDyP9MrkpA7FPu9Wbmuq6dozBqX7Bo50k46MZYmPxkULpmp0qz8hbM_rCwxwyWAv8X_VD3l9J1q82GQV2px0eNnKb6qzZ7A80E4v7kHoi-4ALZ72UT4O4CxF9tjjzjH_0JoTJ8r2uBAuoNvsc8",
            "n": "hfGPH8_QY26dceh-05Q7Go9ZZ5H0_tNMm9FDIEB2CSG1KCMKN8wQH1b_Ot6Cs3dX6PvYkkBt0aXivezLWRE-sRad26Ih6iIS5aVvYXC9PTL3OMu3b0Zsa3zS5IS453mD90fj0kjN0FW-px2821SKw0Fdaei0oYAmYaov_zX3ktygtPSm-ODApDU42dn8weBuvWMoR3ptlqUhkenBiOnmhoZR7XKrQPTPLw-C75x0cVztdcLEFQmH990pZHis-YFOLVbjjRlhv0RITwMlL9MvJXiPaYakQG2-NBlvVNgxF-L44f3rIOtnQajh79Nry6LjbdwUrSCEmLb6dOpM7dnvHQ"
        }
    ]
}`

which parameter shall be used for the "TokenSigningKey"?

I've tried many different random strings and they all worked. By work I mean I could successfully issue JWTs. But I don't think that's the correct way of doing it. Especially if I want to offload the authentication onto another layer (say API gateway), I'm a newbie to JWT/JWK presumably I shall be using a 'private key' for generating the JWTs and use the 'public key' for authentication, right? So do I just create a pair of RSA keys, plug them in and call it a day?

Thanks.

**Comment by dj-nitehawk** [comment]
the jwtbearer static class is nothing more than a simple wrapper around the asp.net jwt code. see here: https://github.com/FastEndpoints/FastEndpoints/blob/ae38f9fc2349724ddcf9e89b2dc571cef0a4bf07/Src/Security/JWTBearer.cs#L143

basically it takes whatever string/secret you provide and creates a symmetric signing key out of it. jwt tokens are then signed with that key. that is the token issuing side. 

on the token verification side, the asp.net auth middleware verifies that the incoming jwts are valid using the same symmetric key based off of the same secret you specify. i.e. the secrets need to match both when you sign the token and also when you verify the token. 

if the same secret is not used, the auth middleware will deny access saying token verification failed. 

as for offloading token generation to a gateway, I think you need to use asymmetric key generation. which I can't advise you on since I haven't had the chance to do it. 

any guide/tutorial on the matter for asp.net should get you sorted on that.

**Comment by isilcala** [comment]
That explains a lot. So if we are doing a symmetric signing key, basically I can just provide an arbitrary string for the "TokenSigningKey" and it is a valid use-case, not violating any best practice, correct?

**Comment by dj-nitehawk** [comment]
correct. just keep it secret from the public. if the secret is leaked, then anybody can sign their own tokens and infiltrate your app.

**Comment by isilcala** [comment]
Perfect. I'll go search asymmetric key separately. 

Thank you for the prompt reply, very helpful.
