### ISSUE TITLE
FastEndpoints performance benchmark

### ISSUE THREAD

**Issue by SViradiya-MarutiTech** [FastEndpoints/FastEndpoints#355]
I cloned FastEndpoints repository, and  Just run Benchmarks using `run.cmd`  file in this Runner project, results was different then provided in https://fast-endpoints.com/benchmarks#asp-net-minimal-api-1k-more-requests-per-second-than-fastendpoints. Results are as below. 

**I had run two three times**
![image](https://user-images.githubusercontent.com/68224794/206378102-9b3fd5ad-ea6c-4c74-a219-9b764a4accf1.png)

So can you please check why FastEndpoints performance is not still promising?

**Comment by dj-nitehawk** [comment]
of course it's not surprising because you cannot compare benchmark results from two different hardware machines.

at a glance it looks like your hardware is roughly 3.6 times slower than my machine.

the thing to note is that even on your machine, fastendpoints is 1.35 times faster than mvc for the same workload. and that's the only thing that matters. it's always gonna be faster than mvc controllers. FE never claims to be faster than minimal apis. even though it sometimes it is on different hardware.

on par with minimal apis means performance will always be within the margin of error when pitting minimal api vs. fastendpoints together.

hope that clears up your confusion.
