### ISSUE TITLE
Post request with no body but having a request binding to a header or url param returns 415 not supported

### ISSUE THREAD

**Issue by rubenmamo** [FastEndpoints/FastEndpoints#384]
Thanks for your work on this library. 

I have a use case where I want to do a post request which has no body whilst getting a value either from a header or from the url.

I have created the following endpoint
```
    public class Endpoint : Endpoint<Request, EmptyResponse>
    {
        public override void Configure()
        {
            Post("/route/path/here");
            AllowAnonymous();
        }

        public override Task HandleAsync(Request r, CancellationToken c)
        {
            return SendAsync(Response);
        }
    }
    public class Request
    {
        [FromHeader("some-header")]
        public string SomeHeader { get; set; }
    }
```

When I try to post via the swagger UI I am getting 415 error.
![image](https://user-images.githubusercontent.com/7700562/219692525-392862f4-f5e7-465b-9d34-da56a23f0ab8.png)

For ease of reference I have created a public repository which showcases this issue: https://github.com/rubenmamo/FastEndpoint-415

Am I doing this incorrectly? Or is there something going wrong in the library for this specific use case?

**Comment by dj-nitehawk** [comment]
do endpoint config like this:
```cs
public override void Configure()
{
    Post("/route/path/here");
    AllowAnonymous();
    Description(x => x.Accepts<Request>("*/*"), clearDefaults: true);
}
```
the reason is, by default when you specify the request dto type, FE automatically adds accepted content-type `application/json`. but marking the one and only property on the dto with `[FromHeader]` removes that property from the swagger schema. and when the incoming post request doesn't contain a body nor `application/json` content-type, the routing middleware blocks the request.

so you'd have to redeclare the accepts metadata like above yourself by clearing the default metadata.

hope that explains it ;-)

**Comment by rubenmamo** [comment]
That is exactly what I needed. Works like a charm.

Thanks for the prompt response and keep up the good work!
