### ISSUE TITLE
Rate limiting feature wrong behavior in integration tests

### ISSUE THREAD

**Issue by DCP-JUNG** [FastEndpoints/FastEndpoints#408]
Hello,
Can you try and confirm or not the following situation ?

### 1. Describe the bug

Using rate-limiting feature on my endpoint, then trying to run an integration test.
Extension method POSTAsync<TEndpoint, TRequest, TResponse> is returning 403 Forbidden by throttling middleware.

![image](https://user-images.githubusercontent.com/71648841/225680101-f2e610cf-09eb-4d7d-8386-06f428ffe127.png)

1) Integration test do only 1 call and the endpoint is configured using Throttle(20, 1)
2) The documentation said the error should be https://fast-endpoints.com/docs/rate-limiting#endpoint-rate-limiting 429 Too many request. (and not 403, related to authorization)

_While in runtime, there is no issue related to 403, everything works perfectly._

### 2. To Reproduce

In endpoint : 

```
        Post("/mowers/execute");
        AllowAnonymous();
        //Set anything you want here
        Throttle(20, 1); // Issue on integration test
```

Then in integration test, using WebApplicationFactory use
`await _client.POSTAsync<TEndoint, TRequest, TResponse>(youRequest);`

### 3. Expected behavior

In integration test with throttling middleware :

1) Endpoint should run the http request if under rate limitation.
2) Throttling middleware should return 429.

### 4. Actual behavior

Throttling middleware always return 403

**Comment by dj-nitehawk** [comment]
it's because during the integration test, the header used to determine a unique client is missing from the request.
here's an example on how to add it to the httpclient:
https://github.com/FastEndpoints/FastEndpoints/blob/0764ce8dce9f892325f58ce2a7f80ae904903e15/Tests/IntegrationTests/FastEndpoints.IntegrationTests/WebTests/AdminTests.cs#L67

if you haven't customized the header name either at the endpoint level or global level, you'd just be doing something like the following:
```cs
client.DefaultRequestHeaders.Add("X-Forwarded-For", "some unique value for this test or a random value if not testing the throttling");
```

and here's where the 403 is being sent from when header reading fails:
https://github.com/FastEndpoints/FastEndpoints/blob/0764ce8dce9f892325f58ce2a7f80ae904903e15/Src/Library/Main/RequestHandler.cs#L20-L31

this behavior is documented here: https://fast-endpoints.com/docs/rate-limiting#header-name
