### ISSUE TITLE
About swagger support

### ISSUE THREAD

**Issue by zfchai** [FastEndpoints/FastEndpoints#437]
- Currently, the underlying dependency of package FastEndpoints. Swagger is using NSwag. AspNetCore,
- Can **Swashbuck. AspNetCore. Swagger** or **IGeekFan. AspNetCore. Knife4jUI** be supported?

**Comment by dj-nitehawk** [comment]
there was swashbuckle support in the beginning. it quickly became a nightmare to maintain two different swagger packages. so only nswag exists now. nswag was chosen because of its extended list of features such as client generation and the ease of development compared to swashbuckle. 

the community is more than welcome to contribute any swagger integration packages modelled after the nswag code.

**Comment by zfchai** [comment]
Can Swagger Enhanced Edition be supported, similar to **IGeekFan.AspNetCore.Knife4jUI** is a more intuitive and user-friendly display page.

**Comment by zfchai** [comment]
# About file handling

- Currently, **FastEndpoints.Swagger** does not support file upload operations. Would you consider enhancing the functionality of this section?

**Comment by dj-nitehawk** [comment]
it is supported:
```cs
public class UploadFile : Endpoint<Request>
{
    public override void Configure()
    {
        Post("upload");
        AllowFileUploads();
        AllowAnonymous();
    }

    public override async Task HandleAsync(Request req, CancellationToken ct)
    {
        await SendAsync(req.TheFile.FileName);
    }
}

public sealed class Request
{
    public IFormFile TheFile { get; set; }
}
```
![image](https://user-images.githubusercontent.com/7043768/233818855-458b84a2-e405-46c7-8404-79fafaf9a834.png)

**Comment by dj-nitehawk** [comment]
> Can Swagger Enhanced Edition be supported, similar to **IGeekFan.AspNetCore.Knife4jUI** is a more intuitive and user-friendly display page.

seems to work:
```cs
var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc();

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints();
app.UseOpenApi();
app.UseKnife4UI(c =>
{
    c.SwaggerEndpoint("/v1/swagger.json", "version 1");
});
app.Run();
```

**Comment by zfchai** [comment]
# About Swagger Grouping

When the dependency feature [ApiExplorerSettings (GroupName="Xxx")] implements webAPI or Endpoint grouping, the concept of version support is unreasonable, such as:

- [ApiExplorerSettings(GroupName = "Xxx")]
- [ApiExplorerSettings(GroupName = "Yyy")]

Both Xxx and YYY groups have v1.0 versions, which are temporarily not supported. The pseudocode is as follows:

- Xxx => Configure().Version("v1.0")
- Yyy => Configure().Version("v1.0")


Parameter description: Xxx and Yyy respectively represent different functional modules.

`protected void Version(int version, int? deprecateAt = null) => Definition.EndpointVersion(version, deprecateAt);`

The parameter in Version should be a string, not an int type.

**Comment by dj-nitehawk** [comment]
FE doesn't use `[ApiExplorerSettings]`.
FE's versioning strategy is a bit different.
please read the versioning doc page couple of times. 
i think you have not fully understood the simplfied model of versioning in FE yet.

basically, a single swagger document `AddSwaggerDoc(...)` is a release group. say for example "v1" or "initial release".
within the v1 release group/swagger doc, only the latest "individual" endpoint version specified by `maxEndpointVersion` will show up for that swagger doc/release group. 

for example, say you have 3 versions of a single endpoint such as this:

- "/api/get-appointment/v1"
- "/api/get-appointment/v2"
- "/api/get-appointment/v3"

obviously the v2 and v3 endpoints should not appear in the "initial release (v1)" swagger doc.
so by configuring the "initial release" swagger doc like the following get's the job done.
only `"/api/get-appointment/v1"` endpoint shows up in this swagger doc.
```cs
    .AddSwaggerDoc(maxEndpointVersion: 1, settings: s =>
    {
        s.DocumentName = "Initial Release (v1)";
        s.Title = "My App";
        s.Version = "v1.0";
    })
```

and... because we don't want `"/api/get-appointment/v1"` and `"/api/get-appointment/v3"` to show up in the v2 (second release) swagger document, we specify the `maxEndpointVersion` of that doc to be `2` like so.
which makes only ` "/api/get-appointment/v2"` show up.
```cs
    .AddSwaggerDoc(maxEndpointVersion: 2, settings: s =>
    {
        s.DocumentName = "Second Release (v2)";
        s.Title = "My App";
        s.Version = "v2.0"; //or if you want, you can call this v1.1 or whatever
    });
```

with this stratergy the `Version(2.x)` doesn't make any sense. there can never be a minor version of an endpoint. minor versioning if needed are done at the swagger doc/release group level.

hope this makes it clear.
not sure if i can explain it any better than that.

**Comment by zfchai** [comment]
I understand what you mean, but you don't understand what I'm expressing.
For the same grouping, the version of the API is definitely incremental, and there is no requirement for the same version number;

However, under different groups, the API version number can be the same, such as:

- The API in Group A can be version v1.0;
- The API in Group B can also be version v1.0;

**Comment by dj-nitehawk** [comment]
that can be achieved like this:
```cs
builder.Services.AddSwaggerDoc(s =>
{
    s.DocumentName = "Group A (v1)";
    s.Title = "My App";
    s.Version = "v1.0";
    s.EndpointFilter(ep => ep.EndpointTags?.Contains("GroupA") is true);
});

builder.Services.AddSwaggerDoc(s =>
{
    s.DocumentName = "Group B (v1)";
    s.Title = "My App";
    s.Version = "v1.0";
    s.EndpointFilter(ep => ep.EndpointTags?.Contains("GroupB") is true);
});
```
tag your endpoints with the correct group it belongs to like this:
```cs
public override void Configure()
{
    ...
    Tags("GroupA");
    Version(1);
}

public override void Configure()
{
    ...
    Tags("GroupB");
    Version(1);
}
```

**Comment by zfchai** [comment]
Okay, that's great. The relevant information in the document needs to be improved!

**Comment by dj-nitehawk** [comment]
it's mentioned here: 
https://fast-endpoints.com/docs/swagger-support#filtering-endpoints

added a bit more detailed here: 
https://fast-endpoints.com/docs/api-versioning#ad-hoc-grouping-of-endpoints

**Comment by zfchai** [comment]
Can **AddSwaGGerDoc.Version(string)** & **Configure(). Version (int)** parameter types be unified?

![image](https://user-images.githubusercontent.com/82487746/233972411-c1fec284-6e57-40b5-9e85-f380c5e01872.png)

**Comment by dj-nitehawk** [comment]
`s.Version` is a string property that comes from nswag. i have no control over that.
so you'll have to take care of that yourself. maybe store some `const` value somewhere and use those for the endpoint config and turn it into a string when setting `v.Version`. choice is yours ;-)

**Comment by zfchai** [comment]
FastEndpoint Configure(). Version (string) parameter type design should be consistent with the string attribute s.Version from nswag, for example:

- Change **Configure(). Version (int)** to **Configure(). Version (string)**

**Comment by dj-nitehawk** [comment]
no can do.
it's gonna break hundreds of endpoints out there.

**Comment by zfchai** [comment]
Why should we consider the int type when setting it at that time? This is very inconsistent with practical use, and it is a serious design flaw!

The more reasonable API version planning is as follows:

- Version number:  **x.y.z**, for example:  **v1.0.0**

Version number parameter meaning:

- X major version number；
- Y minor version number；
- Z Small version number；

This management is more in line with the actual production situation, so using Version (string) is more reasonable.

Sincere suggestion, design a framework, should not be more in line with the actual situation, solve the problem, rather than bring problems, discretionary consideration, thank you very much!

**Comment by dj-nitehawk** [comment]
you can use this instead now: https://github.com/FastEndpoints/FastEndpoints/issues/352#issuecomment-1520363655

**Comment by zfchai** [comment]
https://github.com/FastEndpoints/FastEndpoints/issues/352#issuecomment-1520363655

At present, I think 352 (comment) is a preview version. Will this part remain stable in the official version of Nuget in the future?

# About the DTO model page display of FastEndpoints.Swagger?

The get request of the API in the Swagger page, DTO parameter model, is displayed as an empty object.

When the DTO model is used together for different API requests, whether it is a get or post request method, the DTO model is all empty objects. Affected by get, the API for post requests also displays as empty objects, which feels like a bug.

`Endpoint<TRequest, TResponse>`, the DTO model of TRequest is as follows:

```csharp
public sealed class IdDto
{
    /// <summary>
    ///Business ID
    /// </summary>
    public string Id { get; set; }
}
```

**Comment by zfchai** [comment]
Why is the status marked as Closed before the problem is properly addressed? 

![image](https://user-images.githubusercontent.com/82487746/234162983-f5769a2d-5a29-45fb-9946-4fe7f359a98a.png)

**Comment by dj-nitehawk** [comment]
> Will this part remain stable in the official version of Nuget in the future?

most likely should be final. just wanna get a bit more feedback from the community for any unforeseen edge cases before this gets pushed to a release. even if it does change, it would only affect the way startup is configured and endpoints would not need any change. so you can safely use it in production if you like.

> When the DTO model is used together for different API requests, whether it is a get or post request method, the DTO model is all empty objects.

this matter is documented here: https://fast-endpoints.com/docs/swagger-support#removing-empty-schema
FE is typically used (encouraged to) with vertical slice architecture. so dto ineritance nor dto sharing would be done. in all other cases you can use the above setting to get rid of the empty schema in swagger.

> Why is the status marked as Closed before the problem is properly addressed?

because further discussion on the matter is pointless as there are hundreds of apps already are out there in production with the current design of FE's url based versioning and nobody has ever had an issue with string vs. int versioning of individual endpoints. i think you're having a bit of difficulty in adjusting to the way of "simplified" versioning strategy offered by FE. but no worries now, since you can use the `Asp.Versioning.Http` package and go bananas ;-)
give that a go and post any feedback you have on that other thread.

anywho, FE's url based simple versioning is set in stone and will not change in the foreseeable future as it would be a nightmare to update hundreds/thousands of endpoints already written using `int`s. and honestly, there's really no point as i mentioned before it doesn't align with FE's versioning strategy. i.e. semantic versioning is applied to the swagger doc level and not individual endpoints.

thank you for your input.
