### ISSUE TITLE
About the Parameters Display Scheme on the FastEndpoints.Swagger page

### ISSUE THREAD

**Issue by zfchai** [FastEndpoints/FastEndpoints#439]
- WebAPI combined with native NSwag is shown as follows:

![image](https://user-images.githubusercontent.com/82487746/235123162-1fbc5b78-2cd2-45d6-a64f-7fbc9e37b8e1.png)

- EndPoints combined with native FastEndpoints.Swagger is shown as follows:

![image](https://user-images.githubusercontent.com/82487746/235124141-3d14cd43-8c32-4975-beee-e35c49327165.png)

Native NSwag supports displaying Schema, which makes it easier for developers to interface with API interfaces. 
When will the FastEndpoints.Swagger package adjust its support?

- At present, both responses have Example Value and Scheme

![image](https://user-images.githubusercontent.com/82487746/235124807-a8a18838-d404-4a06-a983-0df05617e9c0.png)

demo => [Solution1 (2).zip](https://github.com/FastEndpoints/FastEndpoints/files/11352624/Solution1.2.zip)

**Comment by dj-nitehawk** [comment]
does asp.net minimal APIs support that? 
if it does, can you show me a screenshot?

**Comment by zfchai** [comment]
Take a look at Demo. There are two Control in it, which are requested by Get and Post.

**Comment by dj-nitehawk** [comment]
in your sample. the GET weather controller has a request body schema. but it doesn't work with swagger ui since GET requests with a body is prohibited by the fetch client. here's what i mean: https://streamable.com/h7jjxu

this is the reason why FE+nswag converts all properties of the request dto to "query paramaters" when the endpoint is a GET request. this way the "try it out" feature in swagger ui works.

anyhow, if you were to use minimal apis like this:
```cs
app.MapGet("/test-get-request", ([FromQuery] FastRequest<MyRequest> r) => Results.Ok(r));
```
it would behave exactly the same as FE+nswag right now. but then you'd have to manually create a static `TryParse()` method on all your dtos.

**Comment by zfchai** [comment]
Whether it is a get or post request, the FastEndpoints.Swagger page should display the Schema information of the request parameters, making it easier for interface callers to understand the XML annotations of each attribute in the DTO model and reducing communication costs between personnel.

This feature should be enhanced. The native NSwag is a Scheme that can display Request Parameters. Don't you think the current FastEndpoints. Swagger page lacks this feature, making it very difficult for developers to understand the meaning of parameters when docking with the interface?

**Comment by dj-nitehawk** [comment]
okay... after going through the source code of nswag, i just figured out a simple solution for ya...
```cs
.AddSwaggerDoc(x => x.AllowReferencesWithProperties = true);
```
that should do the trick.

**Comment by zfchai** [comment]
After adding this code, the result did not solve the 'problem'!

![image](https://user-images.githubusercontent.com/82487746/235202108-29542c9c-976f-453f-aa65-d9c89c666376.png)

demo => [Solution1 (2).zip](https://github.com/FastEndpoints/FastEndpoints/files/11352624/Solution1.2.zip)

![image](https://user-images.githubusercontent.com/82487746/235202489-b2c8c4dd-ee72-496d-8de1-2171bbbb292c.png)

**Comment by dj-nitehawk** [comment]
swagger ui doesn't display a schema tab for query parameters afaik. only shows for request body params.

FE's operation processor turns all GET request dto properties to query params because fetch client doesn't support GET requests with a json body. 

so you can't have a schema tab in swagger ui for get request query params due to above two reasons.

**Comment by dj-nitehawk** [comment]
turning your endpoint to a POST endpoint instead of GET would be the easiest solution. 

other than that, I'm out of ideas. 

good night.

**Comment by zfchai** [comment]
Why was the issue status closed before the problem was properly resolved?

And this is a meaningful and valuable suggestion, with enhanced functionality to improve the efficiency of API interface connection.

I hope you can adopt the suggestions proposed, which is a very valuable suggestion!

**Comment by dj-nitehawk** [comment]
I have no further input to the matter. I've given you all the solutions I have. if you have some fix, send in a PR.

**Comment by zfchai** [comment]
Is it a flaw in the FastEndpoints.Swagger package that encapsulates NSwag? Looking at the screenshot above, when running the WebApplication 1 project in the demo, the webAPI method combined with native NSwag can display Request Parameters Scheme information normally. Why is this?

If the problem is not resolved, do you want to change the status to open so that more people can see the information and provide a better and reasonable solution or PR.

**Comment by dj-nitehawk** [comment]
I told you the reason before. it's a GET request with a json body. even though swagger ui displays the schema tab for it, the try it out feature doesn't work. I showed it to you with a screen recording before. 

because of this reason FE schema processor concerts all dto props to query params. 

I don't know how else to explain it to you. 

no point in reopening it. it works as intended. not really a bug. just a limitation that has no viable solution. 

if you don't like how it is, either submit a PR that doesn't break existing users code bases or look for an alternative package. 

thanks!

**Comment by dj-nitehawk** [comment]
sooo... there's been some progress and now with `v5.9.0.4-beta` you can do the following:
```cs
builder.Services.SwaggerDocument(o =>
{
    o.EnableGetRequestsWithBody = true; //this turns off automatic convesion to query params
    o.DocumentSettings = s =>
    {
        s.DocumentName = "My API";
        s.Version = "v1";
    };
});
```
see changelog [here](https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Library/changelog.md)

**Comment by zfchai** [comment]
`o.EnableGetRequestsWithBody = true;` //this turns off automatic convesion to query params

`TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.`

After adjusting `builder.Services.SwaggerDocument()`, how do you implement modular grouping of api interfaces? 
For example: `tagIndex: 0`
