### ISSUE TITLE
SwaggerUi3Settings - EnableTryItOut property vs DeActivateTryItOut() method

### ISSUE THREAD

**Issue by heldersousa-planetpayment** [FastEndpoints/FastEndpoints#465]
Hi guys.

It looks like `DeActivateTryItOut()` method doesn't do anything at the moment. 

With this code, button "Try it out" is removed
```c#
app.UseSwaggerGen(uiConfig: c =>
{
    c.EnableTryItOut = false;
}
```

With this code, the button "Try it out" stays on the swagger page
```c#
app.UseSwaggerGen(uiConfig: c =>
{
    c.DeActivateTryItOut();
}
```

Documentation (https://fast-endpoints.com/docs/swagger-support#enable-swagger) doesn't say anything about which approach should be used, but if the method exists, it should work, no? Is there a difference in using the property or the method?

I'm using package `fastendpoints.swagger - 5.15.0`

Thanks for your help

**Comment by KateyBee** [comment]
I believe the intellisense/XML documentation clears up the confusion:

https://github.com/FastEndpoints/FastEndpoints/blob/d898f59f628455346f6c9e5997730460cff033cf/Src/Swagger/Extensions.cs#L130-L135

So, the `DeActivateTryItOut()` extension method added by FE is for de-activating the try it out feature by default, because by default the feature is activated (expanded) in the Swagger UI.

On the other-hand, the `EnableTryItOut` property (which is provided by NSwag) dictates whether the button should be shown in the UI in the first place or not.

Hope that explains it...

**Comment by heldersousa-planetpayment** [comment]
Thanks @KateyBee for your answer. Just in case it is not clear to everyone what are the different outcomes, I will try to summarize: 
- Property `EnableTryItOut = true` will make the big blue button "Execute" automatically available to click. If set to `false` that button is gone.
- Method `DeActivateTryItOut()` will require the user to click on "Try it out" to see the "Execute" button if `EnableTryItOut = true`.

### Case 1 - no `Execute` button
```c# 
app.UseSwaggerGen(uiConfig: c =>
{
    c.EnableTryItOut = false;
});
```
![image](https://github.com/FastEndpoints/FastEndpoints/assets/107053506/9ac06f78-bc16-4cd6-aca6-c67abf872814)

### Case 2 - `Execute` button is shown automatically
```c#
app.UseSwaggerGen(uiConfig: c =>
{
    c.EnableTryItOut = true;
});
```
![image](https://github.com/FastEndpoints/FastEndpoints/assets/107053506/48675f56-daef-49f0-8ce6-ac56a27732c7)

### Case 3 - `Execute` button is only shown if user clicks on `Try it out` button
```c#
app.UseSwaggerGen(uiConfig: c =>
{
    c.EnableTryItOut = true;
    c.DeActivateTryItOut();
});
```
![image](https://github.com/FastEndpoints/FastEndpoints/assets/107053506/cbdb20a1-230f-45b5-bc5e-374a7d45d72b)

**Comment by KateyBee** [comment]
@heldersousa-planetpayment Great! That sure is going to be helpful. Thank you!
