### ISSUE TITLE
Single Endpoint Authorization Failure Leads to Overall Authorization Failure

### ISSUE THREAD

**Issue by itsoli91** [FastEndpoints/FastEndpoints#466]
Hi,
Currently, I possess an endpoint as depicted below. As far as I am aware, in fast-endpoints, if any of the Endpoint Authorizations below were to fail, a 403 error would be returned to the requesting entity. Is there any way to change this behavior ? My intention is to return  200 OK even if at least one of the Endpoint Authorizations mentioned below has been successfully passed.

```
    public override void Configure()
    {
        Get("/roles");
        Version(1);
        Description(b =>
        {
            b.Produces(200);
            b.Produces(403);
        });
        Summary(s =>
        {
            s.Summary = "get all roles endpoint.";
            s.Description = "get all roles endpoint.";
        });
        Policies("bss_oss_backend");
        Permissions(ApiIdentityConstants.God, nameof(PermissionEnum.ReadRoles));
    }
```

**Comment by KateyBee** [comment]
Do you mean to say that you'd like to allow access if either the policy "bss_oss_backend" OR `Permissions(...)` passes? If so, I'm afraid that's not how it works in ASP.NET in general.

You'll have to pack all the requirements into one policy and use just that instead of specifying two separate mechanisms.

You can use the [Policy(...)](https://fast-endpoints.com/docs/security#policy-method) builder to do it inside the endpoint itself.

If you think I'm mistaken, please provide a small repro using Minimal APIs which I'd then translate to FastEndpoints.

Thanks!
