### ISSUE TITLE
Unable to test service that uses FastEndpoints events

### ISSUE THREAD

**Issue by frasermclean** [FastEndpoints/FastEndpoints#467]
Hi there, I have a service which publishes an event. I am trying to write unit tests for the service. Due to the way that FE events are published: with an extension method instead of an interface, I am unable to mock the dispatcher like I would if I was using MediatR. 

Any suggestions on a workaround?

**Comment by frasermclean** [comment]
Thanks for the response @KateyBee . In this particular instance, I am not using a full-blown WebApplicationFactory, but rather trying to unit test a service, calling all of its public methods. There are mocked dependencies everything that is injected into the constructor.

**Comment by frasermclean** [comment]
Is there a service registered by Fast Endpoints that could be injected into the constructor? The current method of publishing events seems odd.

**Comment by dj-nitehawk** [comment]
odd is the price we pay for convenience, and it gets the job done ;-)
FE event bus is not a `mediater pattern` implementation, so there's no middle man that needs to be injected.

>  I am not using a full-blown WebApplicationFactory

`Factory.RegisterTestServices()` is not a `WebApplicationFactory`. it's just does some wiring up internally so that fake event handlers can be registered during unit testing. i.e. only if you need the handlers to be executed during testing. if not just, do:
```cs
Factory.RegisterTestServices(_ => {});
```

that allows unit tests to run without throwing an exception when a `PublishAsync()` extension method is encountered.

**Comment by frasermclean** [comment]
Thanks for the response. I will give it a try.
