### ISSUE TITLE
Customize response headers

### ISSUE THREAD

**Issue by Rasmus715** [FastEndpoints/FastEndpoints#490]
Right now the only way to customize response headers is to add them by calling HttpContext.Response.Headers.Add method. 
Is it possible to introduce some sort of attribute, that will define, where the response field belongs, whether it be body, or headers?  
``` cs
public record MyResponse
{
    public List<Item> Items { get; init; } = new();

    [InHeader("Continuation-Token")]
    public string? ContinuationToken;
}
```

A Swagger support for that will be appreciated as well :) 
https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters#how-to-use---response-headers
Similar implementation of that in the Swashbuckle library

**Comment by dj-nitehawk** [comment]
swagger support for response headers has been added in `v5.17.1.26-beta`
```cs
Summary(x =>
{
    x.ResponseHeaders.Add(new(200, "x-some-header")
    {
        Description = "some description",
        Example = 123.45
    });
});
```

generates this:
```json
"responses": {
    "200": {
        "description": "Success",
        "headers": {
            "x-some-header": {
                "description": "some description",
                "schema": {
                    "title": "SystemDouble",
                    "type": "number",
                    "format": "double"
                },
                "example": 123.45
            }
        }
```

regarding adding response headers based on attributes...
this i don't think we will be doing because we'd then have to use reflection in every response sending method to iterate over each property which would incur a perf cost.

you can however [write your own send methods](https://fast-endpoints.com/docs/misc-conveniences#send-methods) targetting the `IEndpoint` interface to do that if you don't mind the perf loss.
