### ISSUE TITLE
PUT binding from route - possibly an issue

### ISSUE THREAD

**Issue by nowakpaw** [FastEndpoints/FastEndpoints#492]
Hi. 
Not sure if this is an error, but I'm pretty sure it's possible with minimal api. 

I have a request: `public record ToggleSettingRequest(int Id);`
It is working perfectly with GET: 
`    [HttpGet("/settings/{Id}/toggle"), AllowAnonymous]
    public sealed class ToggleSettingEndpoint : Endpoint<ToggleSettingRequest>` but not for PUT (where I'm getting 415). 

It's working however with Route<int> (but I don't want to use it there).

**Comment by dj-nitehawk** [comment]
as mentioned here: https://fast-endpoints.com/docs/swagger-support#clearing-default-accepts-produces-metadata

you'd have to clear the default `accpets` metadata like so:

```cs
public override void Configure()
{
    Put("/settings/{Id}/toggle");
    Description(x => x.Accepts<ToggleSettingRequest>());
    AllowAnonymous();
}
```

the reason is because by default `PUT` endpoints are setup with a default `accepts` with a `application/json` content-type: https://fast-endpoints.com/docs/swagger-support#describe-endpoints

and when the incoming request doesn't have that content-type header, it will return a 415 error.
this only a concern when there's no other properties on the request dto other than what's being bound by route parameters,
for example, if your request dto had a property that would be bound from the body such as this;
```cs
ToggleSettingRequest(int Id, string Name)
```
then, the incoming request would have `application/json` content-type and you wouldn't have to do anything else.

**Comment by hardcodet** [comment]
> Couldnt tell you why, but my Accepts doesnt have the empty argument option
> 
> ![Image](https://github.com/user-attachments/assets/43bb56c6-c03b-486a-aa36-6fb9e57593b8)
> 
> FastEndpoints v6.1.0


Just ran into that as well. Add a `using FastEndpoints;` to your class, then you get the parameterless option.
