### ISSUE TITLE
Question: usage with microservice architecture?

### ISSUE THREAD

**Issue by aloksharma1** [FastEndpoints/FastEndpoints#532]
Hello,
I came across your library just a month ago and after doing a bit of testing with small apps I am very impressed with what it does. I have one question here, in a distributed microservice architectures using rebus/cap/mass transit is this library still applicable? I know mass transit have its own implementation of mediatr, but i want to know if this rerp implementation can be used in same way. 

PS: i love the simplicity of this library over cqrs.

**Comment by dj-nitehawk** [comment]
yeah like leuan said, FE is just a wrapper around asp.net minimal apis with a few bells and whistles added such as:
built-in command/event bus, mappers, validators, job queues, etc.

people certainly do build microservices with FE and typically use event-brokers and/or grpc for inter-service communication.

if you have a REST api gateway, you'd be building it with FE because FE is first and foremost a REST api library.

also if you don't want to manage the complexity of a full-blown message broker such as rabbitmq, you can build the first version of your microservices with FE's [grpc offerrings](https://fast-endpoints.com/docs/remote-procedure-calls) to keep things simple at first.
