### ISSUE TITLE
How do I bind query string parameters to a Dictionary?

### ISSUE THREAD

**Issue by jerriep** [FastEndpoints/FastEndpoints#538]
I have the following endpoint:

```
public class ListEndpoint : Endpoint<ListEndpoint.Query, PagedResult<ConnectionModel>>
{
    public class Query
    {
        public ConnectionKind? Kind { get; set; }
        public int? PageNo { get; set; }
        public int? PageSize { get; set; }
        public IDictionary<string, string>? Properties { get; set; }
    }
}
```

I am trying to bind query string parameters to the `Properties` property. I tried passing a query string like the one below, but this does not work. My `Properties` property returns null.

```
GET https://localhost:5003/v2/connections?properties[baseurl]=test
```

I based my attempt on the [documentation for accepted query formats](https://fast-endpoints.com/docs/model-binding#accepted-query-formats).

What confuses me is that if I add a property `public List<int> Test { get; set; }` to my `Query` class and then try and pass the query string parameter `GET https://localhost:5003/v2/connections?test[0]=123`, it also does not work. Based on the docs I linked above I would expect at least this part to work. The only way I can get to bind it to the `Test` property is by passing the query string parameters like `GET https://localhost:5003/v2/connections?test=123&test=456`.

But I digress... Binding to the `List<int>` is not what I want to do. I only did that to test my sanity. I want to bind to a dictionary. Is that possible at all?

Thank you :)

**Comment by KateyBee** [comment]
Minimal APIs doesn't have the ability to bind query parameters to dictionaries. But FastEndpoints provides this support via enabling the clients to send complex objects as JSON strings and running it through STJ for deserialization.

So what you need to do is change the type of your property to `Dictionary<>` instead of `IDictionary<>` because STJ cannot deserialize to interface types.

Then send in the query data as a JSON object like below with a query param name matching the DTO property name like this:

```cs
/test?Properties={"Prop1":"Val1","Prop2":"Val2"}
```

Which results in the dictionary being correctly deserialized as shown below:

![screen-record-1700140801](https://github.com/FastEndpoints/FastEndpoints/assets/134909513/c5e0aea0-4c58-44f7-b92b-174b4fad9085)

Do note however you can't use Swagger UI to post data as JSON as it will always try to break the JSON object into separate query parameters which FE won't accept for deserialization.

**Comment by KateyBee** [comment]
You might be able to just register a [custom value parser](https://fast-endpoints.com/docs/model-binding#custom-value-parsers) instead of implementing a full custom request binder.
