### ISSUE TITLE
Dapr support

### ISSUE THREAD

**Issue by bastiennoel93** [FastEndpoints/FastEndpoints#547]
Have you ever used dapr with FastEndpoint? 

Dapr integrates quite easily with minimal apis .net using the package: 
[https://www.nuget.org/packages/Dapr.AspNetCore](https://www.nuget.org/packages/Dapr.AspNetCore)

`app.MapPost("...", async (...) =>
{
 ...
}).WithTopic(PUB_SUB_NAME, TOPIC_NAME);`

We could integrate it directly into the endpoint configuration in this way: 

`public override void Configure()
    {
        Post("someendpoint");
        Policies("somepolicies");
        WithTopic(PUB_SUB_NAME, TOPIC_NAME);
    }`

What do you think?

**Comment by dj-nitehawk** [comment]
you can use the `WithTopic()`extension methods with fastendpoints too. via the `Options(...)` method that exposes the endpoint builder as shown here: https://fast-endpoints.com/docs/misc-conveniences#endpoint-options

**Comment by bastiennoel93** [comment]
Perfect, thanks for the quick response! 😉

**Comment by bastiennoel93** [comment]
I'm coming back to you because when I integrated dapr with fastendpoints, I had a problem with routing.

When I don't include UseFastEndpoints(), it works fine, the endpoint registration is ok: 
![image](https://github.com/FastEndpoints/FastEndpoints/assets/18250350/73f820b8-c339-47d6-9514-8c0ee7607c15)

When i integrate UseFastEndpoints(), i get the following error:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/18250350/1c45792e-4527-446e-947b-138d94ad6e8c)

I've checked Dapr troubleshooting documentation ([https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-troubleshooting/dotnet-troubleshooting-pubsub/](https://docs.dapr.io/developing-applications/sdks/dotnet/dotnet-troubleshooting/dotnet-troubleshooting-pubsub/)) but it doesn't help. 

I've integrated the following code :
`app.UseFastEndpoints();

app.UseCloudEvents();
app.MapSubscribeHandler();`


Have you seen this error before?

**Comment by dj-nitehawk** [comment]
i don't see anything fastendpoints related in that stack trace. seems to be thrown by dapr.
to be frank, i have zero exposure to dapr, so can't really help without knowing how to replicate the issue exactly.
first try sending that stack trace to dapr people and see what they have to say. because FE is just a wrapper around minimal apis and it should work with anything that supports minimal apis.
if all else fails, can you put together a standalone/ bare minium repro project that i can just run and debug?
