### ISSUE TITLE
Question: about gRPC

### ISSUE THREAD

**Issue by scharada** [FastEndpoints/FastEndpoints#558]
Hi, first, you are doing a great work. keep it up.

i did read about the gRPC introduction to FE. gRPC exits because of its speed and most of all its interoperability.  When you say the feature is built based on grpc core and uses messagepack.  what does it keep and what does it leave out ? can you explain it further please ? can proto still be used with FE? (not vouching for it as i prefer messagepack actually)
thank you in advance.

**Comment by dj-nitehawk** [comment]
FE gRPC offerring trades interoperability for convenience. i.e. both client and server components can only be .NET apps. similarly to [magiconion](https://github.com/Cysharp/MagicOnion).

messagepack's contractless resolver is used. so each message contains the propery/field names. this increases the message payload size a bit. but requires less effort from the developer to code/maintain. basically behaves like json serialization.

so yeah, at the expense of increased payload size and the loss of interoperability, you get a very developer friendly way to do remote procedure calls/pub-sub messaging via gRPC communication protocol.

and... when you do need iteroperability + leanest possible message payload size, there's nothing stopping you from doing regular gRPC in your FE application as usual.

this feature was built mainly because 99% of the time, i don't have non-dotnet applications/microservices communicating with my dotnet apps and maintaining .proto files was just a waste of energy.

hope that clears things up. let me know if you have anymore specific questions.

cheers!

**Comment by scharada** [comment]
thank you.. that clears it.
