### ISSUE TITLE
Integration tests with path parameters

### ISSUE THREAD

**Issue by alexalok** [FastEndpoints/FastEndpoints#573]
Say I have an endpoint with the given url:

`Get("/api/users/{UserId}");`

and the request dto:

```c#
record RequestDto(string UserId);
```

If I call a `GETAsync` method on an endpoint in an integration test I get the following request url generated:

`"/api/users/{UserId}"`

I have a middleware that relies on getting a UserId value from a path like so:

`var userId = HttpContext.Request.RouteValues["userId"]`

which obviously fails because there is not a valid id in the url.

Perhaps I am doing this the wrong way? Or is this scenario currently unsupported and I should specify URL explicitly?

**Comment by dj-nitehawk** [comment]
this is not doable with the routeless integration testing extension methods.
your only option would be to use the following `GETAsync()` overload and specify the route url yourself.
https://github.com/FastEndpoints/FastEndpoints/blob/9623842058151416e42cbbf2433f0134dd6d8706/Src/Library/Testing/HttpClientExtensions.cs#L179-L189

**Comment by simon-schweizer** [comment]
Sorry, but are there any plans to support this?

I definitly want to use typesafe endpoint definitions during testing.
But also need ability to specify route and query parameters manually because my DTOs only contain the parameters from the request body.

Thanks,
Simon

**Comment by alexalok** [comment]
@dj-nitehawk, I am willing to try to do this if you do not object. What I want to do is add an additional processing for a url returned from `IEndpoint.TestURLFor<TEndpoint>()` if it has any route arguments and a dto is present. Then process all arguments one by one trying to replace the current part of url with the value from the corresponding dto property.

**Comment by simon-schweizer** [comment]
That would be great. If you also can support Query Params as well would be nice.

To be honest... until today I did not find a great client generator that really works well based on Swagger Doc using System.Text.Json etc.
There was always so much customizing needed with those tools.
I currently prefer Refit or simply httpclient.

For me it feels not natural to share DTOs (as code) with frontends that contain path/query parameters as properties.
Because clients still have to set the parameters within URL correctly and they "need to know" which DTO properties they can skip because they are not part of the body.
This approach feels ok to me if I use these DTOs only on backend side.

So if you support typed endpoint tests for this scenario would be great :-)

**Comment by alexalok** [comment]
> To be honest... until today I did not find a great client generator that really works well based on Swagger Doc using System.Text.Json etc.
> There was always so much customizing needed with those tools.
> I currently prefer Refit or simply httpclient.

I would suggest trying [Kiota](https://github.com/microsoft/kiota)

**Comment by dj-nitehawk** [comment]
yes FE has [kiota integration](https://fast-endpoints.com/docs/swagger-support#api-client-generation). works like a charm >95% of the time. you just need to get the swagger doc generation right.

**Comment by simon-schweizer** [comment]
Thanks for that hint! Seems that I tried everything else except Kiota... I will check it out today...

@dj-nitehawk for sure there is no direct dependency but as soon as I have a great client generation solution I will switch my DTOs to include path/query params as well which allows me to use typed endpoint class integration testing.
Without have path/query in my DTOs i have to use plain URLs during testing which would be a pain. :-)

**Comment by simon-schweizer** [comment]
@alexalok @dj-nitehawk I tried Kiota and it works really well - thanks for that hint!

BUT I still decided to continue without client generation because now I loose the ability to share the model validator classes between frontend and backend which saved me a lot of time. With Kiota I have to duplicate validation code for my frontend.

I think in some other context this might be OK but in my current project with Blazor+ASP.NET backend I prefer sharing a lot of code for my client/backend project... I mean it's always a trade off.

So I am still open if you have the chance to allow setting of route/query params for typed endpoint tests. :-)

**Comment by dj-nitehawk** [comment]
even with that PR, it still requires the values for route params to be supplied via a [request dto instance](https://github.com/FastEndpoints/FastEndpoints/blob/40a6ca8554a6063f60a280afd59509d5a4c7071f/Tests/IntegrationTests/FastEndpoints/EndpointTests/EndpointTests.cs#L67-L76). since your dto doesn't have properties matching the route params, it's not going to help you with the requirement.

>  I loose the ability to share the model validator classes between frontend and backend

can't you just shove the validator classes in the "shared" project and make both your frontend blazor app and the backend api project reference the shared project (that contains the shared models)?

haven't messed around in blazor for a while, so can't really remember the setup.

if that's not something feasible, what do you have in mind for a possible api/experience for typed integration tests, in situations where you don't have a request dto with all the bits? let's see some code that you'd like FE to manifest ;-)

**Comment by simon-schweizer** [comment]
Yes, this is what I do... I am sharing validation classes between frontend and backend project via shared project.
This works well as long my DTOs are the exact same classes and I am not using separat client generated classes on blazor side.

Right now my DTOs only contain the body part cause I anyhow have to set manually the path/query params on client side using HttpClient/Refit/etc... So my options are:

1. Adding path/query params to DTOs and let Kiota generate my client.
-> Here I am loosing my validator sharing

2. DTOs only contain body part properties and use my own http client (currently Refit)
I have validation classes for these DTOs which I reuse e.g. in forms on blazor side.
-> Works well but can't set path/query params during integration tests.

Nice would be the following... just an idea:

```
public async Task TestTwo()
{
    var result = await App.Client.POSTAsync<AddProduct, UpsertProductApiModel>(new()
    {
        Name = "Some name",
        //etc.
    },
    // Anonymous type passing path / query parameters, could be also a dictionary
    new
    {
        LocationId = 123
    });

    result.Response.StatusCode.Should().Be(HttpStatusCode.OK);
}
```

**Comment by alexalok** [comment]
@simon-schweizer one of the options could be to inherit from your request dto and add the properties related to the route. You can do that in the test project to prevent the inherited class leaking into other parts of the application. Note however that the current implementation only supports route arguments but not query arguments.

**Comment by simon-schweizer** [comment]
@alexalok Ok this seems so far the best option... just tried it out and it works really well :-)
I assumed that the used request class during test must match the request class of the endpoint itself in the way how internal discovery works... but this seems not the case. So yes I think I will go with this approach! 
Thanks for your great support ;-)
