### ISSUE TITLE
How can I get raw request body in preprocess method?

### ISSUE THREAD

**Issue by lujamaharjan** [FastEndpoints/FastEndpoints#578]
```cs
public Task PreProcessAsync(IPreProcessorContext<TRequest> ctx, CancellationToken ct)
    {      
        var requestContent = ReadRequestBody(ctx.HttpContext.Request);
    }

private string ReadRequestBody(HttpRequest request)
    {
        using StreamReader reader = new StreamReader(request.Body, Encoding.UTF8);
        var requestBody = reader.ReadToEndAsync();
        requestBody.Wait();
        return requestBody.Result;
    }
```
I always get empty string " ";

**Comment by nefarius** [comment]
[Have you tried this](https://fast-endpoints.com/docs/model-binding#binding-raw-request-content)?

**Comment by lujamaharjan** [comment]
Hi @nefarius 
Using IPlainTextRequest I can get plain json body. but could you help me to access the body without using reflection.
Currently i am getting using  `ctx.Request.TryGetPropertyValue("key")`

**Comment by dj-nitehawk** [comment]
@lujamaharjan 
by the time control arrives at pre-processors, the `HttpContext.Request.Body` stream has already been consumed by the serializer (STJ). you can use a [bufferring middleware](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/use-http-context?view=aspnetcore-8.0#enable-request-body-buffering) to enable multiple reads, but it's not recommended due to the perf impact.
if you give us more details of why you need to re-read the request body stream, we might be able to give you a better alternative. also you shouldn't be using `.Wait()` on a task. that's a recipe for future trouble.

if i my assumption is correct, you're using a generic pre-processor and you don't know how to read a common property value of the incoming request dto yes?

if that's the case, just implement an interface which enforces the required common property and cast to that interface in the pre-processor. something like this:

```cs
interface IHasCompanyId
{
    int CompanyId { get; set; }
}

sealed class MyRequest : IHasCompanyId
{
    public int CompanyId { get; set; }
}

sealed class MyProcessor<TRequest> : IPreProcessor<TRequest>
{
    public async Task PreProcessAsync(IPreProcessorContext<TRequest> context, CancellationToken ct)
    {
        if (context.Request is IHasCompanyId dto)
        {
            var companyId = dto.CompanyId;
        }
    }
}
```

**Comment by lujamaharjan** [comment]
Thanks
