### ISSUE TITLE
Integration tests do not work when response is a subclass of List<MyDTO>

### ISSUE THREAD

**Issue by kbjorklid** [FastEndpoints/FastEndpoints#588]
Just starting out with Fast Endpoints (and, well, with C# and .NET as well). I thought I'd like to have an explicit response class instead of `List<SomeDTO>`, so that looking at the files it would be easy to discover what the response was. However, the problem is that in my integration test I get a null response.

My response object looks like this:
```csharp
internal class MyOperationResponse : List<SomeDTO>
{
    public MyOperationResponse(IEnumerable<SomeData> data) : base(data) { }
}
```

Endpoint definition:
```csharp
internal class MyOperationEndpoint : EndpointWithoutRequest<MyOperationResponse>
{
    // ...
```

Call in the test:
```csharp
        (HttpResponseMessage? httpResponseMessage, MyOperationResponse? result) =
            await Fixture.Client.GETAsync<MyOperationEndpoint , MyOperationResponse>();
        Assert.NotNull(result); // <--- fails
```

It works when executing through Swagger (I get a list of JSON objects as response, as expected), but as said, does not work when running the tests - a `null` is returned.

By replacing all usages of `MyOperationResponse` with `List<SomeDTO>` the test starts to work as well.

Is this a bug or am I just not supposed to subclass `List` in responses?

**Comment by ardalis** [comment]
I don't recommend subclassing List<SomeDTO> but rather wrapping it. So your response would look like this:

```csharp
internal class MyOperationResponse
{
  public List<SomeDTO> DTOs { get; set; } = new();
}
```

This is a much more flexible approach and I suspect it will work better with your tests. Can you try it?

**Comment by kbjorklid** [comment]
Hi @ardalis , thanks for the response.

Your suggestion works, but it also wraps the response in an object and uses the "dtos" as a key for the list. I suppose this was intentional from your part, and by flexibility you mean that now the response can now be expanded with other properties without breaking compatibility with older clients? Thanks, I might do that.

I'm okay with this / don't need more help, but I'm leaving this open in case this is considered a bug to be fixed.

**Comment by ardalis** [comment]
Right you can add other properties, such as metadata for paging or the date when the information was last updated, etc. Having a custom DTO, rather than inheriting from `List` gives you many potential options with very little lost (your result is now not in the root of the payload... that's it). Good luck!

**Comment by dj-nitehawk** [comment]
@ardalis is spot on with the advice to not subclass a list, and i recommend everyone to follow it.

however, i dug a bit deeper into why exactly it wasn't working and found out that it's because STJ is throwing internally due to not being able to find a parameterless constructor on your dto.

so if you really must, just add a default ctor and it will work.

also starting `v5.21.2.19-beta`, the exception will no longer be swallowed.
