### ISSUE TITLE
Which HTTP client for Blazor WASM when sharing request DTOs containing path/query parameters

### ISSUE THREAD

**Issue by simon-schweizer** [FastEndpoints/FastEndpoints#634]
Hi there,

I have a Blazor WASM app using a ASP.NET Core FastEndpoints Backend.

I am sharing the request models between frontend and backend using a "shared" project.
Right now the request DTOs don't contain any path or query parameters.
It works perfectly fine BUT:

Integration testing using typed endpoints is not working because path and query parameters are not part of my DTOs

Now I am considering to add the path and query parameters to the DTOs as well but I am looking for a HTTP client (like Refit, etc.) that is able to automatically set the properties from DTOs to path and query during request on frontend side...

Right now it seems i have to decide whether i want to have easy testing code and more code for client side requests.
Or I continue sharing my DTOs (which is really nice) but have to specify each URL during tests manually :-(

Any help would be great !!!

Thanks,
Simon

**Comment by dj-nitehawk** [comment]
a good alternative to sharing dtos with a blazor wasm app is to [generate an api client](https://fast-endpoints.com/docs/swagger-support#api-client-generation) based on the swagger spec of the api server.

as for putting route/query parameters in the requet dto, it is a pretty normal thing to do. think of the request dto as just a bag of whatever data that the endpoint handler needs to do it's job. it was designed to be used that way. model binding in FE has the ability to bind data from multiple sources into a request dto without much fuss. makes things simple, convenient and the code highly readable.

the idea that a request dto should only contain properties that comes from just the request body, is something to be discarded. if you really want, you can just [do this](https://fast-endpoints.com/docs/model-binding#binding-to-a-dto-property), to have a bit more clarity/separation for the JSON from the body.

as for adding route support for "route-less integration testing", is something that needs to be investigated and figure out a clean way to do it without breaking existing code. so, can't promise anythin, but will surely be looked into again.

**Comment by tnking83** [comment]
@dj-nitehawk I would like to use the Kiota-generated API client for interacting with my service. However, I'm struggling to integrate it with dependency injection in my Blazor WASM app.

My application leverages Auth0 for user authentication. With Refit, I could easily inject the access token and send it with each HTTP request.  Is there a recommended approach for achieving similar functionality with the Kiota client?

**Comment by dj-nitehawk** [comment]
@tnking83 i believe you just need to plug in an [authentication provider](https://learn.microsoft.com/en-us/openapi/kiota/authentication?tabs=csharp#base-bearer-token-authentication-provider) when instantiating the generated api client. found an example here: https://github.com/microsoft/kiota-samples/issues/3230#issuecomment-1935543479

**Comment by nhwilly** [comment]
Just revisiting this and looking to make sure I'm not being foolish.  I, too, am using Blazor WASM and would like to share my request classes with the endpoints.  These request classes are in a shared library that is available both the API and to the Blazor client.  

I do this for every request and while it seems like a lot of overhead it has clarified a lot of things for me.  The strong typing keeps me from getting sloppy.

Below is my original code.  The `StandardQueryParameters` base class (not included) contains things like order and paging, etc.

Of course, using the `[FromQueryParams]` attribute (not shown) on the `NotificationChannelQueryParameters` property works great until you try to reference FastEndpoints in the WASM app (which I didn't want to do anyway).  I couldn't get anything to even build.

So my solution was to make the `NotificationChannelQueryParameters` property virtual on the shared class, then create a derived class on the server that overrides the property and carries the attribute.  I've shown that at the bottom.  The deserializer picks up the derived version on the server and behaves properly.

My understanding is that it's risky/difficult/impossible - I forget which - to bind request body values on GET requests so this query parameters is the way to do it.

Seems a little hacky to me, but it works.  Is there a better way?  Perhaps more standardized or cleaner?

```csharp
public record GetChannelsRequest() : RequestBase
{
  public const string RouteTemplate = "/api/users/me/NotificationChannels";
  public override string Route => QueryHelpers
    .AddQueryString(
      RouteTemplate,
      Parameters.AsDictionary());

  public NotificationChannelQueryParameters Parameters { get; init; } = new();
}

public record NotificationChannelQueryParameters : StandardQueryParameters
{
  public bool IncludeEmail { get; set; } = true;
  public bool IncludeSms { get; set; } = true;
  public bool IncludePush { get; set; } = true;

  public override Dictionary<string, string> AsDictionary()
  {
    var dictionary = base.AsDictionary();

    if (!IncludeEmail)
      dictionary.Add(nameof(IncludeEmail), IncludeEmail.ToString());

    if (!IncludeEmail)
      dictionary.Add(nameof(IncludeSms), IncludeSms.ToString());

    if (!IncludeEmail)
      dictionary.Add(nameof(IncludePush), IncludePush.ToString());

    return dictionary;
  }
}
```

And here is the fix:
```csharp
internal record GetChannelsRequestWithParameters() : GetChannelsRequest
{
  [FromQueryParams]
  public override NotificationChannelQueryParameters Parameters { get; init; } = new();
}
```

**Comment by dj-nitehawk** [comment]
@nhwilly 

> My understanding is that it's risky/difficult/impossible - I forget which - to bind request body values on GET requests so query parameters is the way to do it.

with FE it's not forbidden or illegal to send in a JSON body in a GET request. it's just that the web browser fetch client doesn't allow GET requests with a body (so swagger ui can't be used to test those endpoints). even though it's not banned by the http spec RFC 7231 afaik. so go hard, send in complex objects as json in the body (from .net clients). much safer/performant than shoving a lot of data in query strings imho.

> [FromQueryParams] attribute works great until you try to reference FastEndpoints in the WASM app

that attribute is located in a .net standard class lib called `FastEndpoints.Attributes`. so you can just reference that from the wasm app. no need to bring in the main `FastEndpoints` package.

btw, `[FromQueryParams]` attribute is undocumented, because we don't want people to really use it. it's not that performant and was only implemented as a stopgap for people migrating from old mvc code.

so our recomendation is (as documented), if you need to send in a complex object, either send it in as a query param but as a [json string](https://fast-endpoints.com/docs/model-binding#accepted-query-formats) - correctly url encoded of course, or just shove it in the body as json even if it's a GET request - we don't discriminate ;-)

hope that clears any doubts...

**Comment by dj-nitehawk** [comment]
@nhwilly forgot to mention. there's a switch you can flip which will stop swagger from auto converting all request dto properties to query params:

```cs
.SwaggerDocument(o => o.EnableGetRequestsWithBody = true);
```
which results in a swagger spec like this:

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/83312235-9281-40b7-9b76-7b026e6219cc)

but due to the restriction imposed by the browser fetch client, you won't be able to submit that. but FE will correctly deserialize and bind to the request dto if the request is done by some other client which allows GET+body.

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/08305862-2ecf-43f3-881e-b17fc305cdb3)

**Comment by nhwilly** [comment]
First off, thanks for the quick response.  Huge factor in why I love this package.

My challenge in that I'm trying to hedge my bets.  Right now, this is a Blazor WASM app, because Blazer Server wasn't going to work for a public facing experience.  I can't even think about Blazor SSR, which behaves more like a typical site - although somehow that seems like a safe bet for at least one of the sites that will access this.  I have concerns about the WASM initial download times.  We'll see.

But just as important is that I'm pretty sure I'll be asked about a native app at some point.  So, I'm trying to make sure that the API endpoints can handle a variety of clients.

And that means that people will be copying/pasting/sharing URL's, complete with query strings, everywhere.

I think that means that putting something in the body won't work.

Since my base classes are centralized, I can try to use the JSON query string approach.  Barring that, I'll fall back to the attribute.

I should note here, with regard to performance, that the only time I use these query strings is when I'm asking for lists of entities.  The parameter count is pretty small for now and the frequency of use is likely to be low.

Great to know I have choices.

Thanks.  And I'll join the Discord server.  Sounds like a good idea for me.
