### ISSUE TITLE
Best Practice if one endpoint has to react different on different permissions

### ISSUE THREAD

**Issue by ReneKochITTitans** [FastEndpoints/FastEndpoints#690]
Hi,

we are using FE for our new SAAS we want to build and we comming to a small challange in which I need help.

We have one simple endpoint e.g. /Users
This will get a list of users.

Now I want to have a permission for that e.g. "UserList" which I give my User with the Role "UserAdmin" (as a team admin I want to see all MY user) and "Admin" (as an admin I want to see ALL user).

Now what is best practice here to solve that ?

Actually I have code like this:

HandleMethod:
if (User.GetRole("Admin")
 // Load Users as Admin
else
 // Load User as UserAdmin with a Filter

I don`t like that approach very much because 
a) when a new Role is born, I have to add it to the if-else which feels like an anti pattern
b) one endpoint has a different meaning depending on who you are (Is that even a problem? I dont know it just feels like... meh)
c) testing for the endpoint will be growing depending on the user roles - we are using endpoint-testing / integration-testing, not unit testing.

Any ideas of a better structure?

**Comment by dj-nitehawk** [comment]
a rule of thumb i like to follow is "an endpoint should be doing one thing and one thing only". so i'd personally make two different endpoints, one for the `Admin` to get a list of all users, and a separate one for the `TeamAdmin` to get a list of just his users. they are infact two separate features/use-cases/user stories from a vertical slice architecture standpoint (even though they both return the exact same response model).

also i like to avoid the use of "Roles" in the traditional sense because roles are just too broad and not granular enough for managing permissions. what i typically use is `permissions` & `permission groups`. a permission group can be thought of as a role but it is more specific, and is nothing more than a colleciton of individual permissions that can be assigned to users upon login. we have source generator based [access control list generation](https://fast-endpoints.com/docs/security#source-generated-access-control-lists) to help with that.

the extreme end of "one endpoint doing multiple things" is stuff like graphql/odata which ends up being more trouble than it's worth in the longrun. so yeah, my advice would be to not be afraid to create as many use-case specific endpoints as necessary. long-term they can evolve independantly of eachother without much trouble.

just my humble opinion... let's see what others have to say...

btw, i'd appreciate it if you could direct discussions that aren't directly FE related to our discord server's `#off-topic` channel in the future.

cheers!
