### ISSUE TITLE
Add QueryParam to swagger without request object

### ISSUE THREAD

**Issue by kevinvenclovas** [FastEndpoints/FastEndpoints#697]
@dj-nitehawk I want to add a QueryParam to my swagger without define a extra request object like this one:

```c#
 public class Request
 {
     [QueryParam]
     public string? Status { get; set; }
}
```

i tried to add this in my summary without the request object but swagger did not show this information:

`s.Params["status"] = "XXXX";`

My full endpoint:

```c#
public class AllUsersEndpoint : EndpointWithoutRequest<IEnumerable<UserListItemResponse>, AllUsersMapper>
{
    public ApplicationUserService ApplicationUserService { get; set; } = null!;

    public override void Configure()
    {

        Summary(s =>
        {
            s.Params["status"] = "xx"; // NOT VISIBLE IN SWAGGER
        });
        Get("users");
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        string? status = Query<string>("status", isRequired: false);
        ...
    }
}
```

**Comment by dj-nitehawk** [comment]
i see...

well, without a request DTO, there's no place to infer query parameter details from.
if it was a route parameter like the following, it will just work:
```cs
public class AllUsersEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("users/{status}");
        AllowAnonymous();
        Summary(
            s =>
            {
                s.Params["status"] = "xx";
            });
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        var status = Route<string>("status");
        await SendAsync(status);
    }
}
```

in minimal apis, the parameter info is inferred from the delegate signature:
```cs
app.MapGet("/users", ([FromQuery] string status) => Results.Ok(status));
```

in FE, since there's no delegate to infer from, the only place that info can be gathered from is the request dto. i.e. request dto is the equivalent of the minimal api request delegate signature. (but in accordance with REPR pattern)

so if there's no request dto, there won't be any automatic addition of swagger params for query strings.

if you really must, you can write your own nswag operation processor to add the query parameters to the operation, but i have no idea from where you'd actually infer the query param details if there's no request dto.

hope you can see why this cannot be done with FE.

thoughts?

**Comment by dj-nitehawk** [comment]
@greg-signi 
the `s.Params` dictionary is only for providing description text for params that already exist. here's such a case where there is no request dto but there is a matching "route" param:

```cs
sealed class MyEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("test/{something}");
        Summary(s => s.Params["something"] = "something route param description");
    }
}
```

which generates this swagger spec:

![Image](https://github.com/user-attachments/assets/19b10bcc-b8e2-4237-88e4-1fb83149dc1c)

there's also situations where user adds params via nswag operation processors, and the dictionary can be used to provide the descriptions for those.

hope that clarifies it...
