### ISSUE TITLE
Dependencies Not Isolated Between Tests in SetupAsync

### ISSUE THREAD

**Issue by JKamsker** [FastEndpoints/FastEndpoints#703]
I need a way to ensure that each test receives a fresh instance of `AppDbContext` to prevent data leakage and interference between test test assembly.

In the current implementation, `SetupAsync` is invoked twice, once per ``TestBase<App>`` implementation. 
However, it receives the `AppDbContext` from the last `ConfigureApp` call, leading to potential data leakage and test interference.

### Code Snippet
```csharp
public class App : AppFixture<Program>
{
    protected override void ConfigureApp(IWebHostBuilder a)
    {
        var name = $"ConnectionTests-{Guid.NewGuid()}";
        // set DatabasePath to :memory: for in-memory database
        a.ConfigureAppConfiguration((_, b) => b.AddInMemoryCollection(new Dictionary<string, string>
        {
            [Constants.Configuration.UseInMemoryDatabase] = "true",
            [Constants.Configuration.DatabasePath] = name
        }!));
    }
  
    protected override async Task SetupAsync()
    {
        {
            using var scope = this.Services.CreateScope();
            var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

            try
            {
                await db.Database.MigrateAsync();
            }
            catch (Exception)
            {
            }
        }
    }
}

// Adding Infrastructure:
// This gets called several times per test, but it receives both "dbPaths" at least once.
services.AddDbContext<AppDbContext>(opt =>
{
    var useInMemory = configuration.GetValue<bool>(Constants.Configuration.UseInMemoryDatabase, false);
    var dbPath = configuration.GetValue<string>(Constants.Configuration.DatabasePath);
    
    if(useInMemory)
    {
        if(string.IsNullOrEmpty(dbPath))
        {
            dbPath = "DefaultName";
        }
        
        var constring = string.Equals(dbPath, Constants.Configuration.InMemoryDatabase) 
            ? "Data Source=:memory:" // non-shared in-memory database
            : $"Data Source={dbPath};Mode=Memory;Cache=Shared"; // shared in-memory database
        
        var keepAliveConnection = new SqliteConnection(constring);
        keepAliveConnection.Open();
        opt.UseSqlite(keepAliveConnection);
    }
    else
    {
        if(string.IsNullOrEmpty(dbPath))
        {
            throw new InvalidOperationException("Database path is not set");
        }
        
        opt.UseSqlite($"Data Source={dbPath}");
    }
});
```

## Problem
`SetupAsync` gets called twice, once per test, but it receives the `AppDbContext` from the last `ConfigureApp` call. This behavior can cause data to persist between tests, breaking test isolation.

- ``ConfigureApp`` is called twice, once per ``TestBase<App>`` implementation. It generates a unique database name for each test.
- The ``AddDbContext`` delegate is called multiple times per test assembly, but it seems to receive the correct database names. (2 Test cases -> 1st db name, 2nd db name, 1st again, exception before 2nd)
- The ``AppDbContext`` in SetupAsync contains always the same database name, the last one from ``ConfigureApp``.

## Steps to Reproduce
1. Implement `SetupAsync` and `ConfigureApp` as shown in the code snippet.
2. Run multiple tests that depend on `AppDbContext`.
3. Observe that `SetupAsync` uses the same `AppDbContext` instance from the last `ConfigureApp` call.

## Expected Behavior
Each test should receive a fresh instance of `AppDbContext` to ensure data isolation between tests.

## Actual Behavior
Tests share the `AppDbContext` instance from the last `ConfigureApp` call, leading to potential data leakage and interference.

## Suggested Fix
Ensure that each test creates and uses a unique `AppDbContext` instance. This can be achieved by modifying the configuration setup to guarantee a new instance per test.

**Comment by dj-nitehawk** [comment]
have you seen this part in the documentation?

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/e0c29bfb-3d75-48e7-b20b-4d83959f9552)

`[DisableWafCache]` attribute disables the internal caching of WAF instances. that should make each test-class completely isolated from eachother. but it won't be able to give you isolation between each test-method of a test-class, because that's not how xunit test-fixtures work. a test-fixture is meant to be a shared resource for all test-methods of a test-class. if you don't want shared state, don't use a test-fixture.

if you want total isolation betweeen each test-method, you're on your own with the vanilla `WebApplicationFactory`. because the design goal of the `AppFixture<TProgram>` is not to provide individual test isolation (which is mostly a unit testing concept). the appfixture is designed specifically for integration-testing to prevent booting up WAFs unnecessarily per test-methods/test-classes to speed up test runs. in a typical integration testing scenario, you only need a few derived `AppFixture<TProgram>` classes each representing a uniquely configured `system-under-test` instance (which you issue requests against). you just need to rethink your data strategy for integration testing in a way that resembles a real web server, where there is only one database and all data goes in there. see this [example project](https://github.com/dj-nitehawk/MiniDevTo/tree/main/Tests).

if you do the typical vanilla WAF instance/database per each test-method, your tests will be running a lot slower and use more computing resources.

hope that clears things up...

**Comment by dj-nitehawk** [comment]
you should really look into using a real sql database via `testcontainers` package because the EF inmemory database doesn't behave exactly as a real db server and your tests might be less valueable because of that. here's an [example](https://gist.github.com/dj-nitehawk/04a78cea10f2239eb81c958c52ec84e0). basically, you'll have a fresh database per each test-class that way. this seems to be the most popular way to do integration testing (with a real database) nowadays.
