### ISSUE TITLE
The Role Claim type for Cookie and JWT should be unified as Conf.SecOpts.RoleClaimType

### ISSUE THREAD

**Issue by bilenth** [FastEndpoints/FastEndpoints#704]
```
CookieAuth.SignInAsync
claimList.AddRange(privs.Roles.Select(r => new Claim(ClaimTypes.Role, r)));

// but

JwtBearer.CreateToken
claimList.AddRange(opts.User.Roles.Select(r => new Claim(Conf.SecOpts.RoleClaimType, r)));
```

**Comment by dj-nitehawk** [comment]
good catch...
fixed in `v5.26.0.3-beta`.
thank you very much 🙏

**Comment by bilenth** [comment]
Hi @dj-nitehawk, thank you very much for your prompt support.

However, when I switched to ·v5.26.0.3-beta·, I encountered a new issue:
For example, I logged in using a cookie and added the role claim "Admin" to it, but when I make a request to the endpoint, I receive a 403 response.
**It seems that the Endpoint.Roles("Admin") is not reading the role claim.**
**I suspect that the role validation in the endpoint still uses ClaimTypes.Role.** But, I haven't found where the Endpoint validate role claim code.
So please take a look at it, or you can also tell me the location of the validation, and I will try to find it.
Thank you for your assistance.

Sample pseudocode:
```
await CookieAuth.SignInAsync(o => 
{
    o.Roles.Add("Admin");
});
......
public class TestEndpoint : EndpointWithoutRequest<string>
{
    public override void Configure()
    {
        Get("Test");
        Roles("Admin");
    }
    public override async Task<string> ExecuteAsync(CancellationToken ct)
    {
        return Task.FromResult("Hello World!");
    }
}
```

**Comment by dj-nitehawk** [comment]
so... after hours of debugging through the asp.net auth middleware, it turns out that the cookie middleware doesn't allow customization of the "role" claim type which defaults `http://schemas.microsoft.com/ws/2008/06/identity/claims/role` which you can [see being set here](https://source.dot.net/#Microsoft.AspNetCore.Authentication/TicketSerializer.cs,187). i.e. when it's cookie authentication, the `ClaimsIdentity` is [instantiated](https://source.dot.net/#Microsoft.AspNetCore.Authentication/TicketSerializer.cs,193) with the default value from `ClaimTypes.Role` for it's [RoleClaimType](https://source.dot.net/#System.Security.Claims/System/Security/Claims/ClaimsIdentity.cs,394) property. which ultimately is where the claim type is matched when `IsInRole()` [method](https://source.dot.net/#System.Security.Claims/System/Security/Claims/ClaimsPrincipal.cs,491) is called.

so obviously, a user with a claim type called `role` (value of `Conf.SecOpts.RoleClaimType`) doesn't match with the authorization requirement which the cookie authorization handler is looking for, which is the long soap value above.

which means, there's nothing we can do about it as there's no customization options available. i'll revert it back to `ClaimTypes.Role` like it was before.

**Comment by dj-nitehawk** [comment]
reverted in `v5.26.0.4-beta`

**Comment by bilenth** [comment]
Hi @dj-nitehawk, thanks to your reminder, I've been searching for a way to cover the [RoleClaimType](https://source.dot.net/#System.Security.Claims/System/Security/Claims/ClaimsIdentity.cs,394), until I came across [another constructor of ClaimsIdentity](https://source.dot.net/#System.Security.Claims/System/Security/Claims/ClaimsIdentity.cs,151), and then I found where it is [instantiated](https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Security/CookieAuth.cs#L57).

Now, based on `v5.26.0.3-beta`, I have modified the code:
```
    public static Task SignInAsync(Action<UserPrivileges> privileges, Action<AuthenticationProperties>? properties = null)
    {
        ...
        if (privs.Roles.Count > 0)
            claimList.AddRange(privs.Roles.Select(r => new Claim(Conf.SecOpts.RoleClaimType, r)));
        ...
        return svc.SignInAsync(
            context: ctx,
            scheme: CookieAuthenticationDefaults.AuthenticationScheme,
            // principal: new(new ClaimsIdentity(claimList, CookieAuthenticationDefaults.AuthenticationScheme)),
            principal: new(new ClaimsIdentity(claimList, CookieAuthenticationDefaults.AuthenticationScheme, null, Conf.SecOpts.RoleClaimType)), // Modified
            properties: props);
    }
```

Then, I tested both **Cookie** and **Jwt** login methods, and the Endpoint.Roles("Admin") method **successfully** validated both. Additionally, the following approach also worked:
```
IHttpContextAccessor _httpContextAccessor;
var roles = _httpContextAccessor.HttpContext?.User?.FindAll(Conf.SecOpts.RoleClaimType).Select(r => r.Value).ToList();
// roles: ["Admin"]
```

Congratulations~

**Comment by dj-nitehawk** [comment]
daaang!!! you're absolutely right...
guess i was looking at the wrong side of the puzzle. i was too focused on the cookie decryption/verification side. it didn't occur to me to look at the role mismatch in cookie creation side.
anywho, good job mate!!! thanks for not giving up and keep looking.
`v5.26.0.5-beta` has been pushed to nuget.

cheers!
