### ISSUE TITLE
Integrate Fastendpoints with the .net 8 Identity module

### ISSUE THREAD

**Issue by AbdoDabbas** [FastEndpoints/FastEndpoints#706]
First of all, thanks a lot for all the efforts put in this great library.

Second,
I was trying to use the .NET 8 new identity as a full package (register users, login, generate bearer token ..etc).
But noticed that it doesn't generate a typical JWT toke, as such, maybe because of that I couldn't use the Policies security method in the Fastendpoints to protect my endpoint, it always gives 401, maybe because the token is not JWT?
If so, is there a way to use the same bearer token generated with the .NET 8 Identity module ?

**Comment by dj-nitehawk** [comment]
have you seen [this example](https://gist.github.com/dj-nitehawk/83a2a863a12f84e65fc4d565657c8673)?
try setting up the middleware pipeline like that.
if that doesn't help, going to need a minimalistic repro project to investigate.

in any case, if you have the correct middleware pipeline setup, the `Policies()` endpoint config method should just work because all it's doing under the hood is creating `[Authorize(Policy = "some_policy")]` attributes and adding it to the endpoint metadata. whatever auth middleware you've setup then reads those `[Authorize]` attributes to determine whether or not to allow access.

also, the ms identity stuff doesn't use JWT tokens by default, and uses cookies if i remember correctly.

so, let's see a repro project to see what you're trying to do...
you can just zip it up and attach here (delete bin/obj folders).

**Comment by dj-nitehawk** [comment]
just tried the following and it works: https://streamable.com/0lw2sn
```cs
var bld = WebApplication.CreateBuilder(args);
bld.Services
   .AddIdentityApiEndpoints<IdentityUser>()
   .AddRoles<IdentityRole>()
   .AddEntityFrameworkStores<MyDbContext>()
   .Services
   .AddDbContext<MyDbContext>(o => o.UseInMemoryDatabase("MyDatabase"))
   .AddAuthorization()
   .AddFastEndpoints()
   .SwaggerDocument();

var app = bld.Build();
app.UseAuthentication()
   .UseAuthorization();
app.MapGroup("/api").WithTags("Identity").MapIdentityApi<IdentityUser>();
app.UseFastEndpoints()
   .UseSwaggerGen();
app.Run();

sealed class ProtectedEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("test");
        Policy(b => b.RequireClaim(ClaimTypes.Name, "blah@blah.com"));
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendAsync("you are authorized!");
    }
}
```

**Comment by AbdoDabbas** [comment]
Thanks a lot for the quick and detailed response, I'll check this locally and I'm sure it'll work.

Regards.

**Comment by AbdoDabbas** [comment]
I think as I mentioned previously, ASP.NET Identity is not using JWT, but anyway for my case it's not important.
