### ISSUE TITLE
Request - Any way to skip registration of command / event bus?

### ISSUE THREAD

**Issue by frasermclean** [FastEndpoints/FastEndpoints#713]
I am already using MediatR in my projects and was wondering if there was any way to skip registration of these services with FastEndpoints? Not sure how much memory this would actually save.

**Comment by frasermclean** [comment]
Was thinking that maybe this feature should be an optional extra in another package Not sure it really belongs in the core functionality.

**Comment by dj-nitehawk** [comment]
there will be no memory allocations unless you actually use commands/events because they're resolved on first use. 

even if you do use it, our buses are more lightweight than mediatr, last I checked. 

you could free up a couple of bytes by removing the following service descriptors: 

https://github.com/FastEndpoints/FastEndpoints/blob/ea8e7815974904a0081ac040f1d952a88f0851b7/Src/Library/Main/MainExtensions.cs#L32

https://github.com/FastEndpoints/FastEndpoints/blob/ea8e7815974904a0081ac040f1d952a88f0851b7/Src/Library/Main/MainExtensions.cs#L38

but really there's no point. they're not doing anything unless commands/events are published.

**Comment by dj-nitehawk** [comment]
btw, creator of mediatr says this: 

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/e566ad6c-00c6-4deb-b061-84666bab3145)

**Comment by frasermclean** [comment]
Fair enough, thanks for the response. I use MediatR because I have shared codebase with API, Azure Functions and Blazor projects which cant all use FastEndpoints.

**Comment by dj-nitehawk** [comment]
yep that's a fair use case 👍
