### ISSUE TITLE
Bind to structs from multiple sources

### ISSUE THREAD

**Issue by Coda17** [FastEndpoints/FastEndpoints#725]
Currently, the model binder does not work with requests that are structs.
Update: This may only affect binding exclusively from route values, TBD.

```csharp
public struct MyRequest
{
    // "Only JSON requests (with an \"application/json\" content-type header) can be deserialized to a DTO type without a constructor! Offending type: [MyRequest]"
    public string MyString { get; set; }
}

public class MyEndpoint : Endpoint<MyRequest>
{
    public override void Configure()
    {
        Get("{MyString}");
    }
    ...
}
```

It would be nice if the model binder was able to bind to structs, similar to how it works in ASP.NET.

## Work-arounds:
There are two perfectly acceptable work-arounds (and one not so great work-around) in the meantime:
1. Defining a constructor.
```csharp
public MyRequest(string myString)
{
     MyString = myString;
}
```
2. A custom RequestBinder<MyRequest>.
```csharp
public class MyRequestBinder : RequestBinder<MyRequest>
{
    public override ValueTask<MyRequest> BindAsync(BinderContext ctx, CancellationToken cancellation)
    {
        return new MyRequest
        {
            MyString = ctx.HttpContext.Request.RouteValues["myString"]?.ToString()!
        };
    }
}

public class MyEndpoint : Endpoint<MyRequest>
{
    public override void Configure()
    {
        Get("{MyString}");
        RequestBinder(new MyRequestBinder());
    }
    ...
}
```
3. ~~Send an empty JSON body in the request:~~ This doesn't properly bind the route parameter but does not give an error message. It constructs the struct and leaves the property as the default value.
```shell
curl -X 'GET' 'htts://{domain}/abc' -H 'Content-Type: application/json' -d '{}'
```

## Other considerations
The binding should work for `structs`, `record structs`, `readonly record structs`, and whether the property has a `set` or `init`, or is `required`.

I am interested in contributing and am currently investigating how to make this enhancement work. It would be nice if there were some contribution guidelines in a CONTRIBUTING.md or similar.

**Comment by dj-nitehawk** [comment]
request DTOs not having a constructor is easy to solve. but the real problem lies in the fact that for all non-STJ binding methods (such as route/query/form fields/etc.), the binder uses [this compiled expression](https://github.com/FastEndpoints/FastEndpoints/blob/56be725f808fc25542d485e7355e3a66ef797cdb/Src/Library/Binder/BinderExtensions.cs#L46-L56) to set values on properties of the dto. the initialized dto instance is passed down to the compiled func for the purpose of setting the value of a given property. the trouble with structs is that they are passed down by value and not by reference. whatever modifications are done to the dto instance within the compiled func is only valid within it's own scope and the original instance remains unchanged. this doesn't work for model binding as the compiled func is used by multiple binding methods and i haven't figured out a way to make the compiled func accept dto instances by `ref`.

so as of now, struct dtos only work for POST methods with a JSON body where STJ deserializes and creates the initial instance. if you have experience with expression trees, maybe you can try to figure out how to pass down the dto instance by `ref`, and that should be the solution to this conundrum.

but then again, i don't see the real point of using a struct as a request dto if it's being passed around `by ref`. in most cases, the properties of the dto would most likely be reference types and only the outer container (dto struct) would be a value type.

so considering all these things, i believe it's not really gonna be worth the effort and maintenance burden that's going to be incurred by implementing full support for struct type request dtos.

thoughts?

**Comment by Coda17** [comment]
Interesting, I thought this might have just been something that was overlooked but it does seem to be more complicated than I originally thought. I'll spend a little more time investigating to see if there's a nice way to make this work, but if not, maybe what would be helpful is better error messaging.

**Comment by Coda17** [comment]
I have one solution _I think_ could eventually work (but haven't gotten it working yet) involving replacing the `Action<object, object?>` with delegates, which loses the clean strong-typing, but seems to be the only way to allow ref parameters in dynamically created methods.

The other solution involves changing the `Action<object, object?>` to `Func<object, object?, TRequest>`, which I believe would work fine, but at the cost of an additional allocation per bind. I'm not really sure how much effect the extra allocations on performance and GC without some benchmarking.

I agree with your reasoning on not being a point to using a struct as a request DTO, so I'm mostly investigating this more out of curiosity. Feel free to close the issue, but I may end up with a PR if I ever figure out a clean way, benchmarking proves the extra allocations don't really matter, or one that just improves error messaging.

**Comment by dj-nitehawk** [comment]
sure no worries. a pr would be most welcome.
btw, i've tried to get the `Func<object, object?, TRequest>` thing going in the past, but just couldn't get the compiled func to return the modified instance, even though it should've worked. possible i missed something. give it a go and let me know if you manage that.

cheers!
