### ISSUE TITLE
Kiota and union types

### ISSUE THREAD

**Issue by OmiCron07** [FastEndpoints/FastEndpoints#745]
I'm using the Kiota client generation with my API using union types (Results) and it does not seem to work, because it only returns the first result type.

This is not supported or am I missing something ? I searched the documentation and nothing is said on that.

**Comment by dj-nitehawk** [comment]
works fine. check this sample: [KiotaTest.zip](https://github.com/user-attachments/files/16445181/KiotaTest.zip)
kiota generated api client only deserializes the success response. everything else is considered errors/exceptions. so you handle errors with try/catch blocks.

**Comment by OmiCron07** [comment]
So, the use of union types is completely useless.

**Comment by dj-nitehawk** [comment]
yeah it doesn't look like kiota does anything specific with union types. at least not yet.
i mean, the swagger spec that gets generated doesn't give any importance to union types either.
i personally don't use the Results<> type since it doesn't really add much value for me. just clutters up my endpoints :-)
