### ISSUE TITLE
ValidationFailed is always false in test

### ISSUE THREAD

**Issue by freetison** [FastEndpoints/FastEndpoints#749]
Given this endpoint
 public override async Task HandleAsync(Appointment req, CancellationToken ct)
    {
        if (ValidationFailed)
        {
            await SendErrorsAsync(cancellation: ct);
            return;
        }

     .. do something 
        await SendAsync("In process", cancellation: ct);
    }

And The unit test:

[Test]  
    public async Task ShouldReturn_BadRequest_When_Appointment_Validation_Fail()
    {
           _fakeAppointmentService = A.Fake<IAppointmentService>();
            var endpoint = Factory.Create<CreateAppointmentEndpoint>(
            ctx =>
            {
                ctx.AddTestServices(
                    s =>
                    {
                        s.AddTransient<IAppointmentService>(_ => _fakeAppointmentService );
                    });
            });

        var req = new Appointment
        {
            Patient = null  // this is required 
        };
        
        await _endpoint.HandleAsync(req, default);

        // Asserts
        _endpoint.ValidationFailed.ShouldBe(true);  // this should be true because the model bind fails.. 

    }

the   if (ValidationFailed)   never happened

**Comment by dj-nitehawk** [comment]
see here: https://github.com/FastEndpoints/FastEndpoints/issues/581#issuecomment-1910588226

**Comment by dj-nitehawk** [comment]
there's no way around it unfortunately.
if the full pipeline (including validator) needs to be tested, it can only be done in an integration test.
with unit tests, the endpoint handler and validator will have to be tested separately.
basically you'd have to mimick the pipeline yourself. because there's no asp.net middleware pipeline during a unit test.
that is why we favor integration tests over unit tests because they take less effort/setup and covers the whole call stack as it would be in a real-life situation.
