### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by mohammad-hosein-shahpouri** [FastEndpoints/FastEndpoints#757]
Does it support GraphQL by it self or it requires some other third-party packages like [GraphQL](https://graphql-dotnet.github.io/) or [GraphQL ASP.NET](https://graphql-aspnet.github.io/)? 
if it doesn't support graphql right now, do you have any plan to support it in future?

**Comment by dj-nitehawk** [comment]
asp.net minimal apis has no graphql support built-in and neither doe FE because of that.
afaik, none of the third party libraries have support for minimal api yet.
if one day microsoft adds graphql support to asp.net minimal apis, FE might be able to add support.
until then, graphql is beyond the scope of FE.
