### ISSUE TITLE
Extend POSTAsync/PATCHAsync/SENDAsync in HttpClientExtensions.cs to allow for different media types

### ISSUE THREAD

**Issue by DominusFlevit** [FastEndpoints/FastEndpoints#804]
Some endpoints have media types other than application/json. In order to allow tests to call them via the Testing extensions, we have to be able to specify the media type or the test will fail with a 415.

Proposed change:
```
public static async Task<TestResult<TResponse>> SENDAsync<TRequest, TResponse>(this HttpClient client,
                                                                               HttpMethod method,
                                                                               string requestUri,
                                                                               TRequest request,
                                                                               bool? sendAsFormData = null,
                                                                               string contentType = "application/json")
```
```
public static Task<TestResult<TResponse>> PATCHAsync<TEndpoint, TRequest, TResponse>(this HttpClient client, TRequest request, bool? sendAsFormData = null, string contentType = "application/json")
     where TEndpoint : IEndpoint where TRequest : notnull
     => PATCHAsync<TRequest, TResponse>(client, GetTestUrlFor<TEndpoint, TRequest>(request), request, sendAsFormData, contentType);
```

**Comment by dj-nitehawk** [comment]
the FE provided httpclient extension methods won't work for anything other than json and form content  because it does this:

https://github.com/FastEndpoints/FastEndpoints/blob/df4051d59dfdad129ae2e2fb3f965343b6ed515a/Src/Library/Testing/HttpClientExtensions.cs#L280-L282

it serializes the request to json because that's [how its supposed to work](https://github.com/FastEndpoints/FastEndpoints/issues/645#issuecomment-2006193588).

so if we allow the request here to be for example "application/xml" the endpoint isn't going to go down the json deserialization path and bind the request correctly.

so, you'll have to use the regular httpclient methods to send requests to endpoints that aren't accepting json or form data.

here's an example:

https://github.com/FastEndpoints/FastEndpoints/blob/df4051d59dfdad129ae2e2fb3f965343b6ed515a/Tests/IntegrationTests/FastEndpoints/MiscTests/MiscTestCases.cs#L8-L30
