### ISSUE TITLE
Using localization with Validator<TRequest>

### ISSUE THREAD

**Issue by robid98** [FastEndpoints/FastEndpoints#815]
Hello,

I encountered an issue with localizing error messages returned by FluentValidation. I created a middleware that sets the culture based on a header value, which works fine for the services. However, it doesn't seem to work properly for the automatic validation in the FastEndpoints. How can I improve this behavior to ensure consistency across both the services and the FastEndpoints validation?

```c#
public async Task InvokeAsync(HttpContext context)
{
    var lang = context.Request.Headers["Accept-Language"].ToString();
    if (lang is not null)
    {
        lang = Culture.GetCulture(lang);
        var culture = new CultureInfo(string.IsNullOrEmpty(lang) ? Culture.EN : lang);
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
    }

    await _next(context);
}
```

It seems that FastEndpoints injects validators as singletons by default, which is causing issues with localization for the error messages. Is there a workaround to have these validators injected as scoped instances, so that localization works correctly for each request?

![image](https://github.com/user-attachments/assets/a803c96f-e1c1-4c33-8cb9-2a3a9b3361fb)

Can you offer some support please, thank you.

**Comment by nhwilly** [comment]
FWIW, I opted out of the inheritance chain. Would that help?

**Comment by dj-nitehawk** [comment]
resolve and use `IStringLocalizer<TValidator>` within the rules like so:
```cs
sealed class MyValidator : Validator<MyRequest>
{
    public MyValidator()
    {
        RuleFor(x => x.Name).Length(5).WithMessage(Resolve<IStringLocalizer<MyValidator>>()["invalid_name"]);
    }
}
```
sample: [LocalizedErrors.zip](https://github.com/user-attachments/files/17706703/LocalizedErrors.zip)

**Comment by nhwilly** [comment]
> @nhwilly Not sure I understood what you suggest. Do you want me to use directly AbstractValidator without using Validator implementation from FastEndpoints?

There's an option to configure without it.  It's in the docs, I forget where.  I thought I had to do it, but I can't remember why.  Perhaps I was sharing a validator with a Blazor client.  I just wasn't sure if that would help. Clearly @dj-nitehawk has the better solution.  As always.

**Comment by dj-nitehawk** [comment]
instantiating a fluentvalidator per request has a significant performance impact. so FE has chosen to go with singleton validators. until we find a use case that requires scoped/transient validators, FE will stick with the current implementation.

**Comment by nhwilly** [comment]
Hmm.  OK.  So, I'm using a modular monolith approach, and each module registers its own validators by calling a shared extension method like so:
```csharp
public static IServiceCollection AddValidatorsFromAssemblyContaining<T>(
  this IServiceCollection services)
{
  // Get the assembly containing the specified type
  var assembly = typeof(T).GetTypeInfo().Assembly;

  // Find all validator types in the assembly
  var validatorTypes = assembly.GetTypes()
      .Where(t => t.GetInterfaces()
              .Any(i => i.IsGenericType &&
                    i.GetGenericTypeDefinition() == typeof(IValidator<>)))
      .ToList();

  // Register each validator with its implemented interfaces
  foreach (var validatorType in validatorTypes)
  {
    var implementedInterfaces = validatorType.GetInterfaces()
        .Where(i => i.IsGenericType &&
                  i.GetGenericTypeDefinition() == typeof(IValidator<>));

    foreach (var implementedInterface in implementedInterfaces)
    {
      services.AddTransient(implementedInterface, validatorType);
    }
  }

  return services;
}
```
Called like this:
```csharp
services.AddValidatorsFromAssemblyContaining<Account>();
```

Are they not all registered at launch?  Or am I actually creating one each time?  Now that I look at it, it seems like I'm creating a transient one.  I wonder what would happen if I just used `AddSingleton` instead of `AddTransient`?

**Comment by dj-nitehawk** [comment]
@nhwilly 
`AddTransient()` doesn't actually create the instance if i remember correctly. the instance is created when something resolves that type from the di container. no matter how you register it, FE will internally obtain it from the container if registered or creates it directly if not registered in di. so you're fine either way.

my suggestion is to avoid that reflection and add the [type discovery source generator](https://fast-endpoints.com/docs/configuration-settings#source-generator-based-startup) to each of your module/projects.

**Comment by nhwilly** [comment]
> @nhwilly `AddTransient()` doesn't actually create the instance if i remember correctly. the instance is created when something resolves that type from the di container. no matter how you register it, FE will internally obtain it from the container if registered or creates it directly if not registered in di. so you're fine either way.
> 
Yes, `AddTransient()` will cause them to be created/destroyed on each call.  Thank you for catching that.  Registering them using `AddSingleton()` suggests (bad word, I know) that they'll be created once and then resolved each time by FE.

Just so I'm sure I understand, without regard to an additional performance boost as mentioned below, if I leave them as transients it's worse than inheriting from `Validator` and if I register them as singletons, it's no worse than inheriting them from `Validator`.  Because if they're no worse as transients, I'll get back to work.  Otherwise, I'll dig into figuring out if singletons cause any issues.  Thanks for explaining this to me.

> my suggestion is to avoid that reflection and add the [type discovery source generator](https://fast-endpoints.com/docs/configuration-settings#source-generator-based-startup) to each of your module/projects.

**Comment by dj-nitehawk** [comment]
the reason i suggested that you just use the `type discovery generator` is because, FE doesn't actually register any validators in the DI container. instead, it just stores the `System.Type` of the validator on the `EndpointDefinition` during startup phase, and only on the first request to an endpoint, is the validator instantiated and cached for subsequent requests using FE's "service resolver" via the following line:

https://github.com/FastEndpoints/FastEndpoints/blob/6f5431029250b02283eda1359f6f3559bed6dcfb/Src/Library/ServiceResolver/ServiceResolver.cs#L30

so you're just doing unnecessary work during startup for each and every one of your module projects.

if you don't like to add the source generator to each of your modules, just let FE know about your assemblies via this:

```cs
bld.Services.AddFastEndpoints(
    o => o.Assemblies =
    [
        typeof(SomeAssemblyName).Assembly,
        typeof(AnotherAssemblyName).Assembly
    ]);
```

**Comment by robid98** [comment]
Thanks @dj-nitehawk, the solution proposed by you is working fine.
