### ISSUE TITLE
Very good library but naming convention is very poor.

### ISSUE THREAD

**Issue by TanvirArjel** [FastEndpoints/FastEndpoints#816]
Please improve the naming convention with the descriptive names. Why the variable names, parameter names are like `abc`, `zyz` etc?

Please at least improve the following:

```
/// <summary>
/// the handler method for the endpoint. this method is called for each request received.
/// </summary>
/// <param name="req">the request dto</param>
/// <param name="ct">a cancellation token</param>
[NotImplemented]
public virtual Task HandleAsync(TRequest req, CancellationToken ct)
    => throw new NotImplementedException();

/// <summary>
/// the handler method for the endpoint that returns the response dto. this method is called for each request received.
/// </summary>
/// <param name="req">the request dto</param>
/// <param name="ct">a cancellation token</param>
[NotImplemented]
public virtual Task<TResponse> ExecuteAsync(TRequest req, CancellationToken ct)
    => throw new NotImplementedException();
```

To

```
/// <summary>
/// the handler method for the endpoint. this method is called for each request received.
/// </summary>
/// <param name="req">the request dto</param>
/// <param name="ct">a cancellation token</param>
[NotImplemented]
public virtual Task HandleAsync(TRequest request, CancellationToken cancellationToken)
    => throw new NotImplementedException();

/// <summary>
/// the handler method for the endpoint that returns the response dto. this method is called for each request received.
/// </summary>
/// <param name="req">the request dto</param>
/// <param name="ct">a cancellation token</param>
[NotImplemented]
public virtual Task<TResponse> ExecuteAsync(TRequest request, CancellationToken cancellationToken)
    => throw new NotImplementedException();
```

Better understanding of naming convention you can take a look at ASP.NET Core library itself.

**Comment by dj-nitehawk** [comment]
thanks for the compliment about the library...
but no thanks for the naming suggestion 😉
we like to break out of the generally accepted mold and do things a bit differently (with good reason).
and by we, i mean mostly me 😜
anywho, if you have a hard aversion to the param names, what you can do is edit these [rider live templates](https://gist.github.com/dj-nitehawk/6493cb85bf3bb20aad5d2fd7814bad15) to your liking and use them to scaffold endpoints instead of using ide completion to override the handler method. or just rename the parameters once the ide completes the override.

khop khun khap!

**Comment by TanvirArjel** [comment]
>we like to break out of the generally accepted mold and do things a bit differently (with good reason).

Making a thing in a possible the worst way cannot be a different way. :)

>and by we, i mean mostly me 😜

You have written the library for the industry and community. So you should follow the industry and community standards.

**Comment by dj-nitehawk** [comment]
wrote the library for my own use and decided to open source it for the benefit of others.
i have a long standing aversion towards the herd mentality in software development.
if i followed convesion and the so called industry standards, this library wouldn't exist.
this whole library is about thinking out of the box and figuring out easier/better ways to do things.
bottom line is i just can't stand unnecessary verbosity in software.
thank you for your opinions!

**Comment by nhwilly** [comment]
Hahaha. 

Going to be really unprofessional here. 

I'm 70 years old. I've seen some things. 

This package is a tour de force of open source. 

I have yet to see any package as complete, well documented and well supported. Anywhere. Full stop. 

You fucking rock. 

Do it your way. No compromise, no prisoners, no blood, no foul. 

I love this package for what it does and what it represents.

**Comment by dj-nitehawk** [comment]
@nhwilly 
appreciate the love my mannn! ❤️❤️❤️
i'm pushing 40 myself. been coding since 15, so yeah...

@TanvirArjel 
sorry if i sounded arrogant in my previous replies.
i'd generally agree with your stance on extremely short variable names, but within the context of an endpoint handler method, the point is kinda moot since 99.9% of people reading the handler code knows what `req` means in that context and avoids/cuts down on the realestate pollution when accessing a lot of properties on the request dto. and for those who do like the pollution, it's just a matter of selecting the variable name and hitting F2 to rename it to whatever they want. no big deal...
