### ISSUE TITLE
Infinite recursion on `[FromBody]` property due to inherited db models

### ISSUE THREAD

**Issue by AnnaSasDev** [FastEndpoints/FastEndpoints#830]
The Swagger documentation fails to load in due time, when using the [FromBody] attribute on the CreateFirstModelRequest.Model property. This causes a significant delay (up to 2.8 minutes) or results in a fetch error for /swagger/v1/swagger.json.

This is probably due to the heavily inherited nature of the model class and which other db models it accesses.
A solution to this issue, is to not use the db model directly as an input to the Request.

Repo that repoduces the issue:
https://github.com/AnnaSasDev/FastEndpoints-RecursionIssue

**Comment by dj-nitehawk** [comment]
looked into this briefly and i think it's bordering on "inheritance misuse" teritory 😜
i can't even wrap my head around the inheritance chain (probably because i'm unfamiliar with the problem domain).
anywho, as this is not a typical usage scenario, i don't think there's a point in spending any effort trying to implement a fix for it.
if it ever pops up again, will definitely look into a fix.
thanks for the repro!
