### ISSUE TITLE
Make global headers defined on FastEndpoint configuration

### ISSUE THREAD

**Issue by fbrum** [FastEndpoints/FastEndpoints#849]
With Swashbuckle Global Header properties could be made enabled or disabled by having an attribute on the method:
```c#
[HeaderDefinition("MyHeaderForPostOperations", "CorrelationId")]
public async Task<IActionResult> PostAsync(CancellationToken cancellationToken)
```
With that on the IOperationFilter we can abort if not defined:
```C#
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
      if (!((IEnumerable<object>) context.MethodInfo.GetCustomAttributes(typeof (HeaderDefinition), false)).Any<object>((Func<object, bool>) (att => att is HeaderDefinitionAttribute headerDefinition && ((IEnumerable<string>) headerDefinition.Names).Contains<string>("CorrelationId"))))
        return;
```

This helps when we need headers that are used by several methods, but not by all. And this option facilitates to make Header properties modular.

I was looking to see if this is possible in FE, but didn't found a way.
I haven't  gone deeper to the code to understand the possibility, but it would be nice to have something similar in the FE Configuration.
My thinking is being able to do something like:
```C#
    public override void Configure()
    {
        Post("Issue");
        AllowAnonymous();
        Description(x => x.ActivateHeader("MyHeaderForPostOperations"));
        Description(x => x.ActivateHeader("CorrelationId"));
```
and on the IOperationFilter that information would be available at OperationProcessorContext.
So for that endpoint if the header is active and the respective Header key is defined by a IOperationFilter  implementation, it would show it on OpenAPI.
To retrieve the value on the endpoint, one would recur to the classic `HttpContext.Request.Headers`

Disclaimer: I'm new to FE so maybe this request is already possible, but I haven't figure it out yet.

**Comment by dj-nitehawk** [comment]
can you have a look at the following: https://github.com/FastEndpoints/FastEndpoints/issues/840#issuecomment-2516953827
and see if that helps?

so the end result would be something like:

```cs
public override void Configure()
{
    Post("Issue");
    AllowAnonymous();
    Tags("ActivateCorrelationId", "ActivateSomeHeader");
}
```

and in the nswag `IOperationProcessor`, you just check if the current endpoint definition has a given tag and add the corresponding header parameter to the swagger spec as shown in the above example.

would that suffice?

**Comment by fbrum** [comment]
Thanks for the quick feedback.
Now I fell bad for my search skills 😂
I search by IOperationProcessor, but that ticket didn't came up.

That would definitely work.
But as a final solution is misusing the Tag purpose of Open API.

So I get that in terms of priority this feature might get pushed down, but would be nice seeing in a long run a clean solution.

Thanks for your great work.

**Comment by dj-nitehawk** [comment]
no worries mate... we're here to help...
the "endpoint tags" are completely different from open-api tags.
endpoint tags are set using `Tags(...)` method and swagger tags are set using `Description(x => x.WithTags(...));`
endpoint tags exist for the sole purpose of [filtering endpoints](https://fast-endpoints.com/docs/configuration-settings#filtering-endpoint-registration) in situations like these via the `EndpointDefinition`.
there is no relationship between "endpoint tags" and "swagger tags" whatsoever.
since FE uses a concept of [auto swagger tagging](https://fast-endpoints.com/docs/swagger-support#swagger-operation-tags), your codebase will most likely not use the `.WithTags(...)` method.
so i believe the above solution is perfectly acceptable.

alternatively, you could add your own custom metadata to the endpoint with an extension method like the following and look for that metadata in the `IOperationProcessor`:

```cs
{
    public override void Configure()
    {
        Description(x => x.ActivateHeader("x-my-header"));
    }
}

static class MyExtensions
{
    public static RouteHandlerBuilder ActivateHeader(this RouteHandlerBuilder b, string headerName)
    {
        b.WithMetadata(new RequestHeader(headerName));
        return b;
    }
}

class RequestHeader(string name)
{
    public string Name { get; set; } = name;
}
```

here's how you can obtain the metadata for the current endpoint in the operation proceossor:

https://github.com/FastEndpoints/FastEndpoints/blob/79794ed475b3571ada5c1ee1a777dc3bb4569903/Src/Swagger/OperationProcessor.cs#L49

**Comment by fbrum** [comment]
That is awesome.
Thank you so much for the deep and clear clarification .
This settles the matter 👍
